//go:build !js || !wasm

package games

// gameDescriptions maps each game's canonical name to its human-readable short
// title (CLI listings / help). Kept in a server/CLI-only file (build tag
// !js || !wasm) so the description strings are NOT compiled into the Cloudflare
// Worker (TinyGo/WASM) binaries, which must stay under the 1 MB gzipped
// free-tier limit. The worker-reachable registry (registry.go) carries only
// Name + Category; descriptions live here. (issue #1459 SSoT for descriptions;
// worker-size split per #2126.)
var gameDescriptions = map[string]string{
	"blackjack":           "BlackJack (ブラックジャック)",
	"poker":               "5-card Draw Poker (ポーカー)",
	"oldmaid":             "Old Maid (ババ抜き)",
	"daifugo":             "Daifugo / Great Fool (大富豪)",
	"bigtwo":              "Big Two (大老二)",
	"sevens":              "Sevens (7並べ)",
	"doubt":               "Doubt (ダウト)",
	"holdem":              "Texas Hold'em (テキサスホールデム)",
	"omaha":               "Omaha Hold'em (オマハホールデム)",
	"omahahilo":           "Omaha Hi-Lo / 8 or Better (オマハ ハイロー)",
	"bigo":                "5 Card Omaha (Big O) (5カードオマハ)",
	"bigohilo":            "5 Card Omaha Hi-Lo (Big O) (5カードオマハ ハイロー)",
	"shortdeck":           "Short Deck (6+ Hold'em) (ショートデック)",
	"pineapple":           "Pineapple Poker (パイナップルポーカー)",
	"crazypineapple":      "Crazy Pineapple Poker (クレイジーパイナップル)",
	"irishpoker":          "Irish Poker (アイリッシュポーカー)",
	"hearts":              "Hearts (ハーツ)",
	"memory":              "Memory / Concentration (神経衰弱)",
	"klondike":            "Klondike Solitaire (ソリティア)",
	"freecell":            "FreeCell (フリーセル)",
	"seahaventowers":      "Seahaven Towers (シーヘイブンタワーズ)",
	"cruel":               "Cruel (クルーエル)",
	"baccarat":            "Baccarat (バカラ)",
	"spades":              "Spades (スペード)",
	"crazyeights":         "Crazy Eights (クレイジーエイト)",
	"ginrummy":            "Gin Rummy (ジンラミー)",
	"indianrummy":         "Indian Rummy (インドラミー)",
	"canasta":             "Canasta (カナスタ)",
	"spider":              "Spider Solitaire (スパイダーソリティア)",
	"napoleon":            "Napoleon (ナポレオン)",
	"indianpoker":         "Indian Poker (インディアンポーカー)",
	"videopoker":          "Video Poker Jacks or Better (ビデオポーカー)",
	"deuceswild":          "Deuces Wild (デューシーズワイルド)",
	"jokerpoker":          "Joker Poker (ジョーカーポーカー)",
	"euchre":              "Euchre (ユーカー)",
	"pyramid":             "Pyramid (ピラミッド)",
	"tripeaks":            "TriPeaks (トリピークス)",
	"cribbage":            "Cribbage (クリベッジ)",
	"threecard":           "Three Card Poker (スリーカードポーカー)",
	"ohhell":              "Oh Hell (オー・ヘル)",
	"ninetynine":          "Ninety-Nine (ナインティナイン)",
	"bridge":              "Contract Bridge (コントラクトブリッジ)",
	"speed":               "Speed (スピード)",
	"gofish":              "Go Fish (ゴーフィッシュ)",
	"pinochle":            "Pinochle (ピノクル)",
	"golf":                "Golf Solitaire (ゴルフ)",
	"pigtail":             "Pig's Tail (ブタのしっぽ)",
	"sevencardstud":       "Seven Card Stud (セブンカードスタッド)",
	"clocksolitaire":      "Clock Solitaire (クロックソリティア)",
	"durak":               "Durak / Fool (ドゥラーク)",
	"fortythieves":        "Forty Thieves (フォーティシーブス)",
	"paigow":              "Pai Gow Poker (パイガオポーカー)",
	"twotenjack":          "Two Ten Jack (ツーテンジャック)",
	"caribbeanstud":       "Caribbean Stud Poker (カリビアンスタッドポーカー)",
	"texasholdembonus":    "Texas Hold'em Bonus Poker (テキサスホールデムボーナスポーカー)",
	"war":                 "War (戦争)",
	"canfield":            "Canfield Solitaire (キャンフィールド)",
	"fiftyone":            "Fifty-one (フィフティワン)",
	"yukon":               "Yukon Solitaire (ユーコン)",
	"russiansolitaire":    "Russian Solitaire (ロシアンソリティア)",
	"whist":               "Whist (ホイスト)",
	"catchten":            "Catch the Ten (スコッチ・ホイスト)",
	"letitride":           "Let It Ride (レット・イット・ライド)",
	"pokersquares":        "Poker Squares (ポーカー・スクエアズ)",
	"cribbagesquares":     "クリベッジ・スクエアズ（4×4に置き、8手をクリベッジで採点）",
	"diplomat":            "ディプロマット（104枚、8列×4枚、スート無視の降順）",
	"royalcotillion":      "ロイヤルコティヨン（104枚、2つ飛ばしで折り返す8本の組札）",
	"tarabish":            "タラビッシュ（36枚2対2のジャス系。J/9が最強、ランとベラのメルド）",
	"baloot":              "バルート（32枚2対2。Sun/Hokomの宣言で序列そのものが入れ替わる）",
	"estimation":          "エスティメーション（湾岸の予想制トリック。的中のみ加点、Dash/Riskで振れ幅が変わる）",
	"israeliwhist":        "イスラエリホイスト（2段階入札。競りで切り札とノルマ、その後全員が個別に宣言）",
	"hokm":                "ホクム（イランの2対2。7トリック先取で即終了、無失点勝ちはKotで2点）",
	"mendikot":            "メンディコット（インドの2対2。4枚の10の取り合い、切り札はフォローできない札で決まる）",
	"bhabhi":              "バービー（インドの3〜7人。フォローできないと場札を全部引き取り、最後に残った1人が敗者）",
	"teendopaanch":        "3-2-5（インド北部の3人専用。3・2・5という別々のノルマが割り当てられる非対称トリックテイキング）",
	"hasenpfeffer":        "ハーゼンプフェファー（ユーカー派生。ジョーカーが最強の切り札、競りは全員参加が義務）",
	"sergeantmajor":       "サージェントメジャー（8-5-3。イギリス軍隊由来の3人用、席順でノルマが8・5・3に固定）",
	"honeymoonbridge":     "ハネムーンブリッジ（2人用ブリッジ。前半13トリックは得点にならず、1トリックごとに山札から1枚ずつ引く）",
	"minibridge":          "ミニブリッジ（ブリッジ入門版。競りの代わりにHCPを公開申告してデクレアラーを決める）",
	"pasur":               "パスール（イランのフィッシング。合計11で取る。絵札は同ランクのみ、場を空にするスールは得点2倍）",
	"snap":                "スナップ（イギリスの反射ゲーム。直前の札と同ランクが続いた瞬間に宣言して場札を総取り）",
	"rollingstone":        "ローリングストーン（アンフレ。フォローできないとトリックを手札に加えられる逆転型。先に出し切れば勝ち）",
	"lingerlonger":        "リンガーロンガー（トリックを取ると山札から1枚補充。手札が尽きた人から脱落し、最後まで持ち続けた1人が勝ち）",
	"pig":                 "ピッグ（ドンキー。4枚揃えた人が黙って鼻に手を当て、気づくのが最後だった1人がP・I・Gの文字をもらう）",
	"stealingbundles":     "スティーリングバンドル（場の同ランクを取るフィッシング。相手の束は一番上のランクが弱点で、束ごと奪える）",
	"cucumber":            "キューカンバー（グルカ。スート無関係で最高ランクを更新し続ける。失点は最終トリックを取った1人だけ）",
	"goofspiel":           "ゴフスピール（GOPS。賞札に全員が同時に伏せて入札し、最高額が取る。手番の無い読み合い）",
	"shelem":              "シェレム（点数そのものを競る。ウィドウ交換と全トリック独占のShelem宣言）",
	"rams":                "ラムス（3〜5人可変のポット式。参加して0トリックだと追加支払い）",
	"reversis":            "レヴェルシ（48枚の回避型。キノラ♥Jと♦Aは追加失点＋チップ、プール総取り）",
	"polignac":            "ポリニャック（ジャックを避ける回避型。♠Jは2倍、capot宣言あり）",
	"slobberhannes":       "スロバーハンネス（最初・最後・♣Qのトリックを避ける回避型）",
	"germanwhist":         "ジャーマンホイスト（前半で表向きの札を取り合い、後半だけが得点）",
	"crazyquilt":          "クレイジーキルト（8×8のキルト、短辺が空いた札だけ取れる）",
	"pageone":             "Page One (ページワン)",
	"reddog":              "Red Dog (レッドドッグ)",
	"badugi":              "Badugi (バドゥーギ)",
	"deucetoseven":        "2-7 Triple Draw (デューストゥセブン)",
	"razz":                "Razz (ラズ)",
	"sevencardstudhilo":   "セブンカードスタッド・ハイロー（8以下5枚のローが成立すればポットを折半、不成立ならハイの総取り）",
	"scorpion":            "Scorpion (スコーピオン)",
	"wasp":                "Wasp (ワスプ)",
	"accordion":           "Accordion (アコーディオン)",
	"trash":               "Trash (トラッシュ)",
	"sevenbridge":         "Seven Bridge (セブンブリッジ)",
	"president":           "President / Scum (プレジデント)",
	"cassino":             "Cassino (カッシーノ)",
	"spanish21":           "Spanish 21 (スパニッシュ21)",
	"calculation":         "Calculation (カルキュレーション)",
	"sirtommy":            "サー・トミー（最古級のペイシェンス）",
	"auldlangsyne":        "オールド・ラング・サイン（4列へ強制配りの古典ソリティア）",
	"soko":                "ソッコ（4枚役を足したカナディアンスタッド）",
	"fourseasons":         "フォーシーズンズ（十字と四隅のラップアラウンド・ソリティア）",
	"colorado":            "コロラド（104枚・20山、昇順4本と降順4本の組札）",
	"bisley":              "ビズリー（昇降2組の基礎札ソリティア）",
	"napoleonssquare":     "ナポレオンズ・スクエア（2デッキの正方形ソリティア）",
	"grandfathersclock":   "グランドファーザーズ・クロック（時計盤ソリティア）",
	"missmilligan":        "ミス・ミリガン（2デッキの高難度ソリティア）",
	"duchess":             "ダッチェス（開始ランクを選ぶリザーブ扇のソリティア）",
	"windmill":            "ウィンドミル（十字に並べる2デッキのソリティア）",
	"americantoad":        "アメリカン・トード（2デッキのカンフィールド系ソリティア）",
	"congress":            "コングレス（8つの山と8つの基礎札の2デッキソリティア）",
	"terrace":             "テラス（色違いで積む2デッキのソリティア）",
	"braid":               "ブレイド（三つ編みリザーブの2デッキソリティア）",
	"pontoon":             "ポンツーン（英国式ブラックジャック・親交代制）",
	"settemezzo":          "セッテ・エ・メッツォ（7.5を目指すイタリアのバンキングゲーム）",
	"niuniu":              "闘牛（5枚から3枚で10の倍数を作る中国のギャンブル）",
	"bura":                "ブラ（36枚・同スート複数出しと31点宣言のロシアのトリックゲーム）",
	"mushi":               "虫（六月七月を抜いた花札40枚・雷札がワイルドの大阪の花合わせ）",
	"toepen":              "トゥーペン（10が最強・Jが最弱の32枚オランダのブラフゲーム）",
	"chineseten":          "撿紅點（合計10か同ランクで取り、赤札だけが得点する中国のフィッシング）",
	"laughandliedown":     "ラフ・アンド・ライダウン（同ランクを1枚か3枚取り、取れなくなったら手札を場に置いて降りる17世紀イングランド）",
	"sjavs":               "シャウス（♣Q♠Q と4枚のJが常時切札、32枚2対2のフェロー諸島トリックテイキング）",
	"loba":                "ロバ（108枚のアルゼンチン式ラミー。ピエルナは異なる3スート、101点で脱落）",
	"skitgubbe":           "シートグッベ（一騎打ちで札を集め、集めた札を出し切るスウェーデンの2段構成）",
	"trex":                "トリックス（王が5種の契約から選ぶ中東の20ディール。ドミノはJ起点で加点）",
	"spiteandmalice":      "Spite and Malice (スパイト・アンド・マリス)",
	"skat":                "Skat (スカート)",
	"shithead":            "Shithead / Karma (シットヘッド)",
	"nertz":               "Nertz / Pounce (ナーツ / パウンス)",
	"slapjack":            "Slapjack (スラップジャック)",
	"egyptianratscrew":    "Egyptian Ratscrew (エジプシャン・ラットスクリュー)",
	"bakersdozen":         "Baker's Dozen (ベーカーズ・ダズン)",
	"tonk":                "Tonk (トンク)",
	"casinowar":           "Casino War (カジノウォー)",
	"pitch":               "Pitch / Setback (ピッチ / セットバック)",
	"dragontiger":         "Dragon Tiger (ドラゴンタイガー)",
	"andarbahar":          "Andar Bahar (アンダーバハール)",
	"botifarra":           "Botifarra (ボティファラ)",
	"rikken":              "Rikken (リッケン)",
	"colourwhist":         "Colour Whist (カラーホイスト)",
	"blackjackswitch":     "Blackjack Switch (ブラックジャック・スイッチ)",
	"montecarlo":          "Monte Carlo Solitaire (モンテカルロ・ソリティア)",
	"contractrummy":       "Contract Rummy (コントラクトラミー)",
	"ultimatetexasholdem": "Ultimate Texas Hold'em (アルティメット・テキサスホールデム)",
	"crescent":            "Crescent Solitaire (クレセント・ソリティア)",
	"mississippistud":     "Mississippi Stud (ミシシッピ・スタッド)",
	"belote":              "Belote (ベロート)",
	"spiderette":          "Spiderette (スパイダレット)",
	"mighty":              "Mighty (マイティ)",
	"oasispoker":          "Oasis Poker (オアシスポーカー)",
	"beleagueredcastle":   "Beleaguered Castle (包囲された城)",
	"streetsandalleys":    "Streets and Alleys (ストリート・アンド・アレイズ)",
	"kingalbert":          "King Albert (キング・アルバート)",
	"flowergarden":        "Flower Garden (フラワーガーデン)",
	"fortyandeight":       "Forty and Eight (フォーティ・アンド・エイト)",
	"agnes":               "Agnes Sorel (アグネス・ソレル)",
	"sultan":              "Sultan of Turkey (スルタン)",
	"piquet":              "Piquet (ピケ)",
	"casinoholdem":        "Casino Hold'em (カジノホールデム)",
	"callbreak":           "Call Break (コールブレイク)",
	"tarneeb":             "Tarneeb (ターニーブ)",
	"highcardflush":       "High Card Flush (ハイカードフラッシュ)",
	"briscola":            "Briscola (ブリスコラ)",
	"gaps":                "Gaps / Montana (ギャップス)",
	"fourcardpoker":       "Four Card Poker (フォーカードポーカー)",
	"rummy500":            "Rummy 500 (500ラム)",
	"eightoff":            "Eight Off (エイトオフ)",
	"russianpoker":        "Russian Poker (ロシアンポーカー)",
	"penguin":             "Penguin (ペンギン)",
	"chinesepoker":        "Chinese Poker (チャイニーズポーカー)",
	"sixcardgolf":         "Six Card Golf (シックスカードゴルフ)",
	"doudizhu":            "Dou Dizhu / Fight the Landlord (斗地主)",
	"truco":               "Truco (トゥルコ)",
	"scopa":               "Scopa (スコパ)",
	"acesup":              "Aces Up (四つ葉のクローバー)",
	"barbu":               "Barbu (バルブ)",
	"macau":               "Macau (マカオ)",
	"thirtyone":           "Thirty-One (サーティワン)",
	"tienlen":             "Tien Len (ティエンレン)",
	"osmosis":             "Osmosis Solitaire (オズモシス / 浸透)",
	"fivehundred":         "500 (Five Hundred / ファイブハンドレッド)",
	"schnapsen":           "Schnapsen / Sixty-Six (シュナプセン / 66)",
	"burraco":             "Burraco (ブラーコ)",
	"yaniv":               "Yaniv (ヤニブ)",
	"gongzhu":             "Gong Zhu (拱猪)",
	"bristol":             "Bristol (ブリストル)",
	"bidwhist":            "Bid Whist (ビッド・ホイスト)",
	"tressette":           "Tressette (トレセッテ)",
	"easthaven":           "Easthaven (イーストヘイブン)",
	"tichu":               "Tichu (ティチュー)",
	"bakersgame":          "Baker's Game (ベーカーズ・ゲーム)",
	"bourre":              "Bourré (ブーレ)",
	"sheepshead":          "Sheepshead (シープスヘッド)",
	"doppelkopf":          "Doppelkopf (ドッペルコップ)",
	"mus":                 "Mus (ムス)",
	"tute":                "Tute (トゥーテ)",
	"sueca":               "Sueca (スエカ)",
	"fortyfives":          "Auction Forty-Fives (フォーティファイブズ)",
	"twentynine":          "Twenty-Nine / 29 (トゥエンティナイン)",
	"klaverjas":           "Klaverjas (クラヴァヤス)",
	"manille":             "Manille (マニーユ)",
	"marias":              "Mariáš (マリアーシュ)",
	"sedma":               "Sedma (セドマ)",
	"solowhist":           "Solo Whist (ソロ・ホイスト)",
	"knockoutwhist":       "Knockout Whist (ノックアウト・ホイスト)",
	"nap":                 "Nap / Napoleon (ナップ)",
	"preference":          "Préférence (プレフェランス)",
	"ganjifa":             "Ganjifa (ガンジファ)",
	"vira":                "Vira (ヴィーラ)",
	"spoilfive":           "Spoil Five / Maw (スポイル・ファイブ)",
	"courtpiece":          "Court Piece / Rang (コートピース)",
	"bezique":             "Bezique (ベジーク)",
	"ecarte":              "Écarté (エカルテ)",
	"threecardbrag":       "Three Card Brag (スリーカード・ブラグ)",
	"teenpatti":           "Teen Patti (ティーンパッティ)",
	"scopone":             "Scopone (スコポーネ)",
	"escoba":              "Escoba (エスコバ)",
	"handandfoot":         "Hand and Foot (ハンド・アンド・フット)",
	"conquian":            "Conquian (コンキャン)",
	"chinchon":            "Chinchón (チンチョン)",
	"kalooki":             "Kalooki (カルーキ)",
	"threethirteen":       "Three Thirteen (スリー・サーティーン)",
	"mao":                 "Mao (マオ)",
	"spoons":              "Spoons (スプーン)",
	"kemps":               "Kemps (ケムプス)",
	"cuckoo":              "Cuckoo (カッコー)",
	"pishti":              "Pişti (ピシュティ)",
	"cuarenta":            "Cuarenta (クアレンタ)",
	"fivecardstud":        "Five Card Stud (ファイブカードスタッド)",
	"faro":                "Faro (ファロ)",
	"openfacechinese":     "Open Face Chinese Poker / OFC (オープンフェイス・チャイニーズポーカー)",
	"russianbank":         "Russian Bank / Crapette (ロシアンバンク/クラペット)",
	"labellelucie":        "La Belle Lucie (ラ・ベル・ルーシー)",
	"simplesimon":         "Simple Simon (シンプル・サイモン)",
	"doubleklondike":      "Double Klondike / Gargantua (ダブル・クロンダイク/ガルガンチュア)",
	"blackhole":           "Black Hole (ブラックホール)",
	"beggarmyneighbour":   "Beggar-My-Neighbour (ビガー・マイ・ネイバー)",
	"allfours":            "All Fours / Seven Up (オールフォーズ/セブンアップ)",
	"prsi":                "Prší (プルシー/チェコ版クレイジーエイト)",
	"jass":                "Jass (Schieber) (ヤス/シーバー)",
	"gaigel":              "Gaigel (ガイゲル)",
	"tysiac":              "Thousand / Tysiąc (サウザンド/トゥシオンツ)",
	"calabresella":        "Calabresella / Terziglio (カラブレセッラ/テルツィーリオ)",
	"ombre":               "Ombre / Hombre (オンブル)",
	"ulti":                "Ulti / Ultimó (ウルティ)",
	"king":                "King (キング)",
	"cinch":               "Cinch / Double Pedro (シンチ/ダブルペドロ)",
	"loo":                 "Loo / Lanterloo (ルー)",
	"basra":               "Basra / Bastra (バスラ)",
	"tablanet":            "Tablanet / Tablić (タブラネット)",
	"trenteetquarante":    "Trente et Quarante / Rouge et Noir (トラント・エ・カラント)",
	"guts":                "Guts (ガッツ)",
	"bouillotte":          "Bouillotte (ブイヨット)",
	"primero":             "Primero / Primiera (プリメロ)",
	"michigan":            "Michigan / Newmarket (ミシガン)",
	"watten":              "Watten (ヴァッテン)",
	"carioca":             "Carioca (カリオカ)",
	"samba":               "Samba (サンバ)",
	"anaconda":            "Anaconda / Pass the Trash (アナコンダ)",
	"machiavelli":         "Machiavelli (マキャヴェッリ)",
	"pan":                 "Panguingue / Pan (パングインゲ)",
	"wizard":              "Wizard (ウィザード)",
	"oichokabu":           "Oicho-Kabu (おいちょかぶ)",
	"rook":                "Rook (ルーク)",
	"koikoi":              "Koi-Koi (こいこい)",
	"gostop":              "Go-Stop / Godori (ゴーストップ)",
	"hachihachi":          "Hachi-Hachi (八八)",
	"frenchtarot":         "French Tarot (フレンチタロット)",
	"koenigrufen":         "Königrufen / Tarock (ケーニッヒルーフェン)",
	"aluette":             "Aluette (アリュエット)",
	"minchiate":           "Minchiate (ミンキアーテ)",
	"tarocchini":          "Tarocchini (タロッキーニ)",
	"scarto":              "Scarto (スカルト)",
	"cego":                "Cego (チェゴ)",
	"zheng":               "Zheng Shangyou (ジェンシャンヨウ)",
	"nainjaune":           "ル・ナン・ジョーヌ（5区画の盤を持つフランスのストップス。スート無関係にランクが上がり、Kで止まる）",
	"kille":               "キッレ（専用42枚デッキのスウェーデン版カックー。カッコウ・軽騎兵・豚・騎士・宿屋の5種の絵札が交換を壊す）",
	"klaberjass":          "クラバーヤス（ジャス系の2人用祖型。切札J=20点・9=14点、シーケンス申告、失敗で全得点を譲るベート）",
	"kaiser":              "カイザー（カナダの34枚デッキ。♥5=+5点・♠3=-3点、キティ2枚、ビッド未達は宣言額がマイナス）",
	"boston":              "ボストン（18世紀ホイスト系。ミゼールがトリック宣言の間に挟まる15段の宣言表、ちょうど1トリックのピッコリッシモ）",
	"vint":                "ヴィント（ロシア式ブリッジ。ダミー無し、両チームが取ったトリックを得点、♠が最弱でNTが最強）",
	"bideuchre":           "ビッド・ユーカー（24枚をちょうど配り切りキティ無し。最低3、親だけ同額で奪える。NTローは9が最強）",
	"sixbidsolo":          "シックスビッド・ソロ（36枚を11枚ずつ＋ウィドウ3枚。6段階のビッドが目標点と精算額を切り替える。ミゼールは0トリックでなく0点）",
	"karnoffel":           "カルニッフェル（現存最古の名前付きカードゲーム。最強はJ、7の悪魔はリード時のみ強い。3/4/5は絵札に負ける）",
	"literature":          "リテラチャー（8抜き48枚の推理型フィッシング。6人3対3、味方の手札も非公開。宣言は3通りで所在を誤ると無効）",
	"guandan":             "掼蛋（108枚2デッキの大貧民。4人2対2、レベル札はAより強く♥2枚はワイルド。1着2着の独占で4段階昇級）",
	"shengji":             "升级／拖拉机（108枚2デッキのポイントトリック。25枚ずつ配り底牌8枚。レベル札は全スートが切札、点を集めるのは守備側で80点で交代）",
	"popejoan":            "ポープ・ジョーン（♦8を抜いた51枚。8区画の盤にディーラーが15枚置き、トランプの札で回収する）",
	"poch":                "ポッホ（32枚・9区画の盤を使う3段階構成。取られなかった区画のチップは持ち越される）",
	"zwicker":             "ツヴィッカー（55枚のドイツ北部フィッシング。A・絵札は2つの値を持ち、場を空にするとZwickで1点）",
	"desmoche":            "デスモチェ（9枚配りのニカラグア式ラミー。ちょうど10枚を組めた者がポットを取り、誰も組めなければ持ち越し）",
}

// descriptionCache aliases gameDescriptions (kept for internal call sites).
var descriptionCache = gameDescriptions

// Descriptions returns Name->Description for every registered game. The
// returned map is the package's cached copy — callers must not mutate it.
func Descriptions() map[string]string {
	return descriptionCache
}

// Description returns the description for a single game by name, or "" if
// name is unknown.
func Description(name string) string {
	return descriptionCache[name]
}
