//go:build !js || !wasm

package games

// gameDescriptions maps each game's canonical name to its human-readable short
// title (CLI listings / help). Kept in a server/CLI-only file (build tag
// !js || !wasm) so the description strings are NOT compiled into the Cloudflare
// Worker (TinyGo/WASM) binaries, which must stay under the 1 MB gzipped
// free-tier limit. The worker-reachable registry (registry.go) carries only
// Name + Category; descriptions live here. (issue #1459 SSoT for descriptions;
// worker-size split per #2126.)
var gameDescriptions = map[string]string{
	"blackjack":           "BlackJack (ブラックジャック)",
	"poker":               "5-card Draw Poker (ポーカー)",
	"oldmaid":             "Old Maid (ババ抜き)",
	"daifugo":             "Daifugo / Great Fool (大富豪)",
	"bigtwo":              "Big Two (大老二)",
	"sevens":              "Sevens (7並べ)",
	"doubt":               "Doubt (ダウト)",
	"holdem":              "Texas Hold'em (テキサスホールデム)",
	"omaha":               "Omaha Hold'em (オマハホールデム)",
	"omahahilo":           "Omaha Hi-Lo / 8 or Better (オマハ ハイロー)",
	"bigo":                "5 Card Omaha (Big O) (5カードオマハ)",
	"bigohilo":            "5 Card Omaha Hi-Lo (Big O) (5カードオマハ ハイロー)",
	"shortdeck":           "Short Deck (6+ Hold'em) (ショートデック)",
	"pineapple":           "Pineapple Poker (パイナップルポーカー)",
	"crazypineapple":      "Crazy Pineapple Poker (クレイジーパイナップル)",
	"irishpoker":          "Irish Poker (アイリッシュポーカー)",
	"hearts":              "Hearts (ハーツ)",
	"memory":              "Memory / Concentration (神経衰弱)",
	"klondike":            "Klondike Solitaire (ソリティア)",
	"freecell":            "FreeCell (フリーセル)",
	"seahaventowers":      "Seahaven Towers (シーヘイブンタワーズ)",
	"cruel":               "Cruel (クルーエル)",
	"baccarat":            "Baccarat (バカラ)",
	"spades":              "Spades (スペード)",
	"crazyeights":         "Crazy Eights (クレイジーエイト)",
	"ginrummy":            "Gin Rummy (ジンラミー)",
	"indianrummy":         "Indian Rummy (インドラミー)",
	"canasta":             "Canasta (カナスタ)",
	"spider":              "Spider Solitaire (スパイダーソリティア)",
	"napoleon":            "Napoleon (ナポレオン)",
	"indianpoker":         "Indian Poker (インディアンポーカー)",
	"videopoker":          "Video Poker Jacks or Better (ビデオポーカー)",
	"deuceswild":          "Deuces Wild (デューシーズワイルド)",
	"jokerpoker":          "Joker Poker (ジョーカーポーカー)",
	"euchre":              "Euchre (ユーカー)",
	"pyramid":             "Pyramid (ピラミッド)",
	"tripeaks":            "TriPeaks (トリピークス)",
	"cribbage":            "Cribbage (クリベッジ)",
	"threecard":           "Three Card Poker (スリーカードポーカー)",
	"ohhell":              "Oh Hell (オー・ヘル)",
	"ninetynine":          "Ninety-Nine (ナインティナイン)",
	"bridge":              "Contract Bridge (コントラクトブリッジ)",
	"speed":               "Speed (スピード)",
	"gofish":              "Go Fish (ゴーフィッシュ)",
	"pinochle":            "Pinochle (ピノクル)",
	"golf":                "Golf Solitaire (ゴルフ)",
	"pigtail":             "Pig's Tail (ブタのしっぽ)",
	"sevencardstud":       "Seven Card Stud (セブンカードスタッド)",
	"clocksolitaire":      "Clock Solitaire (クロックソリティア)",
	"durak":               "Durak / Fool (ドゥラーク)",
	"fortythieves":        "Forty Thieves (フォーティシーブス)",
	"paigow":              "Pai Gow Poker (パイガオポーカー)",
	"twotenjack":          "Two Ten Jack (ツーテンジャック)",
	"caribbeanstud":       "Caribbean Stud Poker (カリビアンスタッドポーカー)",
	"texasholdembonus":    "Texas Hold'em Bonus Poker (テキサスホールデムボーナスポーカー)",
	"war":                 "War (戦争)",
	"canfield":            "Canfield Solitaire (キャンフィールド)",
	"fiftyone":            "Fifty-one (フィフティワン)",
	"yukon":               "Yukon Solitaire (ユーコン)",
	"russiansolitaire":    "Russian Solitaire (ロシアンソリティア)",
	"whist":               "Whist (ホイスト)",
	"catchten":            "Catch the Ten (スコッチ・ホイスト)",
	"letitride":           "Let It Ride (レット・イット・ライド)",
	"pokersquares":        "Poker Squares (ポーカー・スクエアズ)",
	"pageone":             "Page One (ページワン)",
	"reddog":              "Red Dog (レッドドッグ)",
	"badugi":              "Badugi (バドゥーギ)",
	"deucetoseven":        "2-7 Triple Draw (デューストゥセブン)",
	"razz":                "Razz (ラズ)",
	"scorpion":            "Scorpion (スコーピオン)",
	"wasp":                "Wasp (ワスプ)",
	"accordion":           "Accordion (アコーディオン)",
	"trash":               "Trash (トラッシュ)",
	"sevenbridge":         "Seven Bridge (セブンブリッジ)",
	"president":           "President / Scum (プレジデント)",
	"cassino":             "Cassino (カッシーノ)",
	"spanish21":           "Spanish 21 (スパニッシュ21)",
	"calculation":         "Calculation (カルキュレーション)",
	"sirtommy":            "サー・トミー（最古級のペイシェンス）",
	"bisley":              "ビズリー（昇降2組の基礎札ソリティア）",
	"napoleonssquare":     "ナポレオンズ・スクエア（2デッキの正方形ソリティア）",
	"spiteandmalice":      "Spite and Malice (スパイト・アンド・マリス)",
	"skat":                "Skat (スカート)",
	"shithead":            "Shithead / Karma (シットヘッド)",
	"nertz":               "Nertz / Pounce (ナーツ / パウンス)",
	"slapjack":            "Slapjack (スラップジャック)",
	"egyptianratscrew":    "Egyptian Ratscrew (エジプシャン・ラットスクリュー)",
	"bakersdozen":         "Baker's Dozen (ベーカーズ・ダズン)",
	"tonk":                "Tonk (トンク)",
	"casinowar":           "Casino War (カジノウォー)",
	"pitch":               "Pitch / Setback (ピッチ / セットバック)",
	"dragontiger":         "Dragon Tiger (ドラゴンタイガー)",
	"blackjackswitch":     "Blackjack Switch (ブラックジャック・スイッチ)",
	"montecarlo":          "Monte Carlo Solitaire (モンテカルロ・ソリティア)",
	"contractrummy":       "Contract Rummy (コントラクトラミー)",
	"ultimatetexasholdem": "Ultimate Texas Hold'em (アルティメット・テキサスホールデム)",
	"crescent":            "Crescent Solitaire (クレセント・ソリティア)",
	"mississippistud":     "Mississippi Stud (ミシシッピ・スタッド)",
	"belote":              "Belote (ベロート)",
	"spiderette":          "Spiderette (スパイダレット)",
	"mighty":              "Mighty (マイティ)",
	"oasispoker":          "Oasis Poker (オアシスポーカー)",
	"beleagueredcastle":   "Beleaguered Castle (包囲された城)",
	"streetsandalleys":    "Streets and Alleys (ストリート・アンド・アレイズ)",
	"kingalbert":          "King Albert (キング・アルバート)",
	"flowergarden":        "Flower Garden (フラワーガーデン)",
	"fortyandeight":       "Forty and Eight (フォーティ・アンド・エイト)",
	"agnes":               "Agnes Sorel (アグネス・ソレル)",
	"sultan":              "Sultan of Turkey (スルタン)",
	"piquet":              "Piquet (ピケ)",
	"casinoholdem":        "Casino Hold'em (カジノホールデム)",
	"callbreak":           "Call Break (コールブレイク)",
	"tarneeb":             "Tarneeb (ターニーブ)",
	"highcardflush":       "High Card Flush (ハイカードフラッシュ)",
	"briscola":            "Briscola (ブリスコラ)",
	"gaps":                "Gaps / Montana (ギャップス)",
	"fourcardpoker":       "Four Card Poker (フォーカードポーカー)",
	"rummy500":            "Rummy 500 (500ラム)",
	"eightoff":            "Eight Off (エイトオフ)",
	"russianpoker":        "Russian Poker (ロシアンポーカー)",
	"penguin":             "Penguin (ペンギン)",
	"chinesepoker":        "Chinese Poker (チャイニーズポーカー)",
	"sixcardgolf":         "Six Card Golf (シックスカードゴルフ)",
	"doudizhu":            "Dou Dizhu / Fight the Landlord (斗地主)",
	"truco":               "Truco (トゥルコ)",
	"scopa":               "Scopa (スコパ)",
	"acesup":              "Aces Up (四つ葉のクローバー)",
	"barbu":               "Barbu (バルブ)",
	"macau":               "Macau (マカオ)",
	"thirtyone":           "Thirty-One (サーティワン)",
	"tienlen":             "Tien Len (ティエンレン)",
	"osmosis":             "Osmosis Solitaire (オズモシス / 浸透)",
	"fivehundred":         "500 (Five Hundred / ファイブハンドレッド)",
	"schnapsen":           "Schnapsen / Sixty-Six (シュナプセン / 66)",
	"burraco":             "Burraco (ブラーコ)",
	"yaniv":               "Yaniv (ヤニブ)",
	"gongzhu":             "Gong Zhu (拱猪)",
	"bristol":             "Bristol (ブリストル)",
	"bidwhist":            "Bid Whist (ビッド・ホイスト)",
	"tressette":           "Tressette (トレセッテ)",
	"easthaven":           "Easthaven (イーストヘイブン)",
	"tichu":               "Tichu (ティチュー)",
	"bakersgame":          "Baker's Game (ベーカーズ・ゲーム)",
	"bourre":              "Bourré (ブーレ)",
	"sheepshead":          "Sheepshead (シープスヘッド)",
	"doppelkopf":          "Doppelkopf (ドッペルコップ)",
	"mus":                 "Mus (ムス)",
	"tute":                "Tute (トゥーテ)",
	"sueca":               "Sueca (スエカ)",
	"fortyfives":          "Auction Forty-Fives (フォーティファイブズ)",
	"twentynine":          "Twenty-Nine / 29 (トゥエンティナイン)",
	"klaverjas":           "Klaverjas (クラヴァヤス)",
	"manille":             "Manille (マニーユ)",
	"marias":              "Mariáš (マリアーシュ)",
	"sedma":               "Sedma (セドマ)",
	"solowhist":           "Solo Whist (ソロ・ホイスト)",
	"knockoutwhist":       "Knockout Whist (ノックアウト・ホイスト)",
	"nap":                 "Nap / Napoleon (ナップ)",
	"preference":          "Préférence (プレフェランス)",
	"spoilfive":           "Spoil Five / Maw (スポイル・ファイブ)",
	"courtpiece":          "Court Piece / Rang (コートピース)",
	"bezique":             "Bezique (ベジーク)",
	"ecarte":              "Écarté (エカルテ)",
	"threecardbrag":       "Three Card Brag (スリーカード・ブラグ)",
	"teenpatti":           "Teen Patti (ティーンパッティ)",
	"scopone":             "Scopone (スコポーネ)",
	"escoba":              "Escoba (エスコバ)",
	"handandfoot":         "Hand and Foot (ハンド・アンド・フット)",
	"conquian":            "Conquian (コンキャン)",
	"chinchon":            "Chinchón (チンチョン)",
	"kalooki":             "Kalooki (カルーキ)",
	"threethirteen":       "Three Thirteen (スリー・サーティーン)",
	"mao":                 "Mao (マオ)",
	"spoons":              "Spoons (スプーン)",
	"kemps":               "Kemps (ケムプス)",
	"cuckoo":              "Cuckoo (カッコー)",
	"pishti":              "Pişti (ピシュティ)",
	"cuarenta":            "Cuarenta (クアレンタ)",
	"fivecardstud":        "Five Card Stud (ファイブカードスタッド)",
	"faro":                "Faro (ファロ)",
	"openfacechinese":     "Open Face Chinese Poker / OFC (オープンフェイス・チャイニーズポーカー)",
	"russianbank":         "Russian Bank / Crapette (ロシアンバンク/クラペット)",
	"labellelucie":        "La Belle Lucie (ラ・ベル・ルーシー)",
	"simplesimon":         "Simple Simon (シンプル・サイモン)",
	"doubleklondike":      "Double Klondike / Gargantua (ダブル・クロンダイク/ガルガンチュア)",
	"blackhole":           "Black Hole (ブラックホール)",
	"beggarmyneighbour":   "Beggar-My-Neighbour (ビガー・マイ・ネイバー)",
	"allfours":            "All Fours / Seven Up (オールフォーズ/セブンアップ)",
	"prsi":                "Prší (プルシー/チェコ版クレイジーエイト)",
	"jass":                "Jass (Schieber) (ヤス/シーバー)",
	"gaigel":              "Gaigel (ガイゲル)",
	"tysiac":              "Thousand / Tysiąc (サウザンド/トゥシオンツ)",
	"calabresella":        "Calabresella / Terziglio (カラブレセッラ/テルツィーリオ)",
	"ombre":               "Ombre / Hombre (オンブル)",
	"ulti":                "Ulti / Ultimó (ウルティ)",
	"king":                "King (キング)",
	"cinch":               "Cinch / Double Pedro (シンチ/ダブルペドロ)",
	"loo":                 "Loo / Lanterloo (ルー)",
	"basra":               "Basra / Bastra (バスラ)",
	"tablanet":            "Tablanet / Tablić (タブラネット)",
	"trenteetquarante":    "Trente et Quarante / Rouge et Noir (トラント・エ・カラント)",
	"guts":                "Guts (ガッツ)",
	"bouillotte":          "Bouillotte (ブイヨット)",
	"primero":             "Primero / Primiera (プリメロ)",
	"michigan":            "Michigan / Newmarket (ミシガン)",
	"watten":              "Watten (ヴァッテン)",
	"carioca":             "Carioca (カリオカ)",
	"samba":               "Samba (サンバ)",
	"anaconda":            "Anaconda / Pass the Trash (アナコンダ)",
	"machiavelli":         "Machiavelli (マキャヴェッリ)",
	"pan":                 "Panguingue / Pan (パングインゲ)",
	"wizard":              "Wizard (ウィザード)",
	"oichokabu":           "Oicho-Kabu (おいちょかぶ)",
	"rook":                "Rook (ルーク)",
	"koikoi":              "Koi-Koi (こいこい)",
	"gostop":              "Go-Stop / Godori (ゴーストップ)",
	"hachihachi":          "Hachi-Hachi (八八)",
	"frenchtarot":         "French Tarot (フレンチタロット)",
	"koenigrufen":         "Königrufen / Tarock (ケーニッヒルーフェン)",
	"scarto":              "Scarto (スカルト)",
	"cego":                "Cego (チェゴ)",
	"zheng":               "Zheng Shangyou (ジェンシャンヨウ)",
}

// descriptionCache aliases gameDescriptions (kept for internal call sites).
var descriptionCache = gameDescriptions

// Descriptions returns Name->Description for every registered game. The
// returned map is the package's cached copy — callers must not mutate it.
func Descriptions() map[string]string {
	return descriptionCache
}

// Description returns the description for a single game by name, or "" if
// name is unknown.
func Description(name string) string {
	return descriptionCache[name]
}
