# Stage 1: Build React frontend
FROM node:24-alpine AS frontend-builder

WORKDIR /app

# Copy pre-existing public assets (images, css, fonts, js)
# that are not generated by the React build
COPY public/ ./public/

WORKDIR /app/frontend

# Install dependencies in a separate layer so this step is only
# re-run when package.json or package-lock.json changes
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

# Copy remaining frontend source and build
# Output goes to ../public (i.e. /app/public) per vite.config.ts
COPY frontend/ ./
RUN npm run build

# Stage 2: Build Go binary
FROM golang:1.24-alpine AS go-builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

# Copy only Go source files for better layer cache efficiency
COPY main.go .
COPY entities/ ./entities/
COPY usecases/ ./usecases/
COPY interface_adapters/ ./interface_adapters/
COPY frameworks_drivers/ ./frameworks_drivers/
RUN CGO_ENABLED=0 GOOS=linux go build -o go_trumpcards .

# Stage 3: Final production image
FROM alpine:3.21

WORKDIR /app

RUN apk --no-cache add ca-certificates && \
    addgroup -S appgroup && \
    adduser -S appuser -G appgroup

COPY --from=go-builder --chown=appuser:appgroup /app/go_trumpcards .
COPY --from=frontend-builder --chown=appuser:appgroup /app/public ./public

USER appuser

# Use a non-privileged port; the server reads the PORT environment variable
ENV PORT=8080
EXPOSE 8080

CMD ["./go_trumpcards", "web"]
