# Stage 1: Build React frontend
# Pinned to a specific digest for reproducible builds
FROM node:24-alpine@sha256:d88d203cab4ee6fa4897d8286f3caea2e9cf48db77176042fca2f4ac4a4414ce AS frontend-builder

WORKDIR /app

# Copy pre-existing public assets (images, css, fonts, js)
# that are not generated by the React build
COPY public/ ./public/

WORKDIR /app/frontend

# Upgrade npm to 11.x to match the version required by package.json
RUN npm install -g npm@11

# Install dependencies in a separate layer so this step is only
# re-run when package.json or package-lock.json changes
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

# Copy remaining frontend source and build
# Output goes to ../public (i.e. /app/public) per vite.config.ts
COPY frontend/ ./
RUN npm run build

# Stage 2: Build Go binary
# Pinned to a specific digest for reproducible builds
FROM golang:1.26-alpine@sha256:d4c4845f5d60c6a974c6000ce58ae079328d03ab7f721a0734277e69905473e5 AS go-builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

# Copy only Go source files for better layer cache efficiency
COPY cmd/ ./cmd/
COPY internal/ ./internal/
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o go_trumpcards ./cmd/server

# Stage 3: Final production image
# Pinned to a specific digest for reproducible builds
FROM alpine:3.21@sha256:22e0ec13c0db6b3e1ba3280e831fc50ba7bffe58e81f31670a64b1afede247bc

WORKDIR /app

# Create non-root user/group first, then install packages — all in one
# layer to minimise image size
RUN addgroup -S appgroup && \
    adduser -S appuser -G appgroup && \
    apk --no-cache add ca-certificates

COPY --from=go-builder --chown=appuser:appgroup /app/go_trumpcards .
COPY --from=frontend-builder --chown=appuser:appgroup /app/public ./public

USER appuser

# Use a non-privileged port; the server reads the PORT environment variable
ENV APP_ENV=production
ENV PORT=8080
EXPOSE 8080

CMD ["./go_trumpcards"]
