# Stage 1: Build React frontend
FROM node:24-alpine AS frontend-builder

WORKDIR /app

# Copy pre-existing public assets (images, css, fonts, js)
# that are not generated by the React build
COPY public/ ./public/

# Install frontend dependencies
COPY frontend/package.json frontend/package-lock.json ./frontend/
WORKDIR /app/frontend
RUN npm ci

# Copy frontend source and build
# Output goes to ../public (i.e. /app/public) per vite.config.ts
COPY frontend/ ./
RUN npm run build

# Stage 2: Build Go binary
FROM golang:1.24-alpine AS go-builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o go_trumpcards .

# Stage 3: Final production image
FROM alpine:3.21

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY --from=go-builder /app/go_trumpcards .
COPY --from=frontend-builder /app/public ./public

EXPOSE 80

CMD ["./go_trumpcards", "web"]
