name = "go-trumpcards-casino"
main = "../../build/casino/worker.mjs"
compatibility_date = "2024-09-23"

[vars]
CORS_ALLOWED_ORIGINS = ""

[[rules]]
type = "CompiledWasm"
globs = ["../../build/casino/*.wasm"]
