/**
 * AI Game Concierge — per-game profile vector.
 *
 * Each vector slot is aligned with the option order declared in
 * `discoverAxes.ts` (a wire-format break in `AXES.<axis>.options`
 * cascades through every profile here). Values are integers in
 * `0..PROFILE_MAX` (= 5), where 5 means "this option describes the
 * game perfectly" and 0 means "this option is a poor fit."
 */
export interface GameProfile {
  /**
   * Indexed by mood option `profileIdx` (quiet_focus=0, lively=1,
   * thoughtful=2, quick=3). Q1 reads [0,1]; Q2 reads [2,3].
   */
  readonly mood: readonly [number, number, number, number];
  /**
   * Indexed by skill option `profileIdx` (beginner=0, intermediate=1,
   * advanced=2, learning_rules=3). Q2's `prefer_familiar` inverts
   * slot 3 via option polarity.
   */
  readonly skill: readonly [number, number, number, number];
  /**
   * Indexed by social option `profileIdx` (solo=0, vs_cpu=1,
   * with_friends=2, casual_play=3, serious_play=4). Slots 3+4 measure
   * how well the game suits "軽く流す" vs "真剣勝負" play.
   */
  readonly social: readonly [number, number, number, number, number];
  /**
   * Indexed by theme option `profileIdx` (casino=0, european=1,
   * western=2, japanese_household=3, showy=4, subdued=5). Slots 4+5
   * measure presentation style (派手な演出 vs 渋い雰囲気).
   */
  readonly theme: readonly [number, number, number, number, number, number];
}

/** A single game route with its path and navigation label i18n key. */
export interface GameRoute {
  path: string;
  labelKey: string;
  /** Emoji icon displayed next to the game name in navigation. */
  icon: string;
  /**
   * PascalCase component name without the `Page` suffix. Used by `App.tsx` to
   * `import.meta.glob`-resolve the matching `pages/<page>Page.tsx` module.
   * Defaults can't be inferred from `path` alone because some routes don't
   * follow the simple "/foo → FooPage" convention (e.g., `/` → BlackJackPage,
   * `/pigtail` → PigsTailPage, `/spiteandmalice` → SpiteAndMalicePage).
   */
  page: string;
  /** Per-axis profile vector used by `/discover` recommendation scoring. */
  profile: GameProfile;
}

/** A category grouping related game routes with a category label i18n key. */
export interface GameCategory {
  labelKey: string;
  /** Emoji icon displayed next to the category name in navigation. */
  icon: string;
  routes: readonly GameRoute[];
}

/** Game routes organized by category for grouped navigation display. */
export const gameCategories: readonly GameCategory[] = [
  {
    labelKey: 'nav.category.table',
    icon: '🎰',
    routes: [
      {
        path: '/',
        labelKey: 'nav.blackjack',
        icon: '🃏',
        page: 'BlackJack',
        profile: { mood: [3, 2, 3, 5], skill: [5, 5, 3, 4], social: [3, 5, 2, 5, 3], theme: [5, 1, 1, 1, 3, 1] },
      },
      {
        path: '/spanish21',
        labelKey: 'nav.spanish21',
        icon: '🇪🇸',
        page: 'Spanish21',
        profile: { mood: [3, 2, 3, 4], skill: [3, 5, 4, 2], social: [3, 5, 2, 3, 3], theme: [5, 1, 1, 1, 3, 1] },
      },
      {
        path: '/baccarat',
        labelKey: 'nav.baccarat',
        icon: '💎',
        page: 'Baccarat',
        profile: { mood: [2, 3, 1, 5], skill: [5, 3, 1, 5], social: [3, 5, 1, 5, 2], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/threecard',
        labelKey: 'nav.threecard',
        icon: '🎴',
        page: 'ThreeCard',
        profile: { mood: [3, 3, 2, 5], skill: [5, 5, 2, 4], social: [3, 5, 2, 5, 2], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/caribbeanstud',
        labelKey: 'nav.caribbeanstud',
        icon: '🏝️',
        page: 'CaribbeanStud',
        profile: { mood: [2, 3, 3, 3], skill: [3, 5, 3, 3], social: [3, 5, 2, 3, 3], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/oasispoker',
        labelKey: 'nav.oasispoker',
        icon: '🌴',
        page: 'OasisPoker',
        profile: { mood: [2, 3, 4, 3], skill: [3, 4, 4, 3], social: [3, 5, 2, 3, 4], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/russianpoker',
        labelKey: 'nav.russianpoker',
        icon: '🪆',
        page: 'RussianPoker',
        profile: { mood: [2, 3, 5, 3], skill: [3, 5, 5, 3], social: [3, 5, 2, 3, 4], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/texasholdembonus',
        labelKey: 'nav.texasholdembonus',
        icon: '🤠',
        page: 'TexasHoldemBonus',
        profile: { mood: [2, 3, 4, 3], skill: [3, 4, 4, 2], social: [3, 5, 2, 3, 4], theme: [5, 2, 1, 1, 4, 2] },
      },
      {
        path: '/casinoholdem',
        labelKey: 'nav.casinoholdem',
        icon: '🎰',
        page: 'CasinoHoldem',
        profile: { mood: [2, 4, 3, 4], skill: [4, 5, 3, 3], social: [3, 5, 2, 4, 3], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/ultimatetexasholdem',
        labelKey: 'nav.ultimatetexasholdem',
        icon: '♠️',
        page: 'UltimateTexasHoldem',
        profile: { mood: [2, 4, 5, 2], skill: [2, 4, 5, 2], social: [3, 5, 2, 2, 5], theme: [5, 2, 1, 1, 4, 2] },
      },
      {
        path: '/paigow',
        labelKey: 'nav.paigow',
        icon: '🀄',
        page: 'PaiGow',
        profile: { mood: [4, 2, 5, 1], skill: [2, 4, 5, 1], social: [3, 5, 2, 2, 4], theme: [4, 1, 1, 3, 3, 2] },
      },
      {
        path: '/chinesepoker',
        labelKey: 'nav.chinesepoker',
        icon: '🐉',
        page: 'ChinesePoker',
        profile: { mood: [4, 2, 5, 1], skill: [1, 5, 5, 1], social: [3, 5, 2, 2, 4], theme: [4, 1, 1, 3, 4, 2] },
      },
      {
        path: '/letitride',
        labelKey: 'nav.letitride',
        icon: '🎰',
        page: 'LetItRide',
        profile: { mood: [2, 3, 2, 4], skill: [4, 4, 2, 3], social: [3, 5, 2, 4, 2], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/reddog',
        labelKey: 'nav.reddog',
        icon: '🐕',
        page: 'RedDog',
        profile: { mood: [3, 3, 1, 5], skill: [5, 3, 1, 5], social: [3, 5, 2, 5, 2], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/casinowar',
        labelKey: 'nav.casinowar',
        icon: '⚔️',
        page: 'CasinoWar',
        profile: { mood: [3, 4, 1, 5], skill: [5, 2, 1, 5], social: [3, 5, 2, 5, 2], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/oichokabu',
        labelKey: 'nav.oichokabu',
        icon: '🎴',
        page: 'OichoKabu',
        profile: { mood: [3, 4, 1, 5], skill: [5, 3, 1, 5], social: [3, 5, 2, 5, 2], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/trenteetquarante',
        labelKey: 'nav.trenteetquarante',
        icon: '🔴',
        page: 'TrenteEtQuarante',
        profile: { mood: [3, 4, 1, 5], skill: [5, 2, 1, 5], social: [3, 5, 2, 5, 2], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/dragontiger',
        labelKey: 'nav.dragontiger',
        icon: '🐉',
        page: 'DragonTiger',
        profile: { mood: [3, 4, 1, 5], skill: [5, 2, 1, 5], social: [3, 5, 2, 5, 2], theme: [5, 0, 0, 2, 4, 1] },
      },
      {
        path: '/blackjackswitch',
        labelKey: 'nav.blackjackswitch',
        icon: '🔀',
        page: 'BlackJackSwitch',
        profile: { mood: [2, 3, 4, 3], skill: [2, 4, 5, 2], social: [3, 5, 2, 3, 4], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/mississippistud',
        labelKey: 'nav.mississippistud',
        icon: '🚢',
        page: 'MississippiStud',
        profile: { mood: [3, 3, 4, 3], skill: [3, 5, 4, 2], social: [3, 5, 2, 3, 4], theme: [5, 1, 2, 1, 4, 1] },
      },
      {
        path: '/highcardflush',
        labelKey: 'nav.highcardflush',
        icon: '♣️',
        page: 'HighCardFlush',
        profile: { mood: [3, 3, 2, 4], skill: [5, 4, 2, 4], social: [3, 5, 2, 4, 2], theme: [5, 1, 1, 1, 4, 1] },
      },
      {
        path: '/fourcardpoker',
        labelKey: 'nav.fourcardpoker',
        icon: '🃏',
        page: 'FourCardPoker',
        profile: { mood: [3, 3, 3, 3], skill: [4, 5, 3, 3], social: [3, 5, 2, 3, 3], theme: [5, 1, 1, 1, 4, 1] },
      },
    ],
  },
  {
    labelKey: 'nav.category.poker',
    icon: '♠️',
    routes: [
      {
        path: '/poker',
        labelKey: 'nav.poker',
        icon: '🂡',
        page: 'Poker',
        profile: { mood: [2, 3, 4, 3], skill: [3, 5, 4, 3], social: [1, 3, 5, 3, 4], theme: [3, 1, 3, 2, 3, 2] },
      },
      {
        path: '/holdem',
        labelKey: 'nav.holdem',
        icon: '🤠',
        page: 'Holdem',
        profile: { mood: [2, 4, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 2, 5], theme: [3, 1, 3, 1, 3, 1] },
      },
      {
        path: '/omaha',
        labelKey: 'nav.omaha',
        icon: '4️⃣',
        page: 'Omaha',
        profile: { mood: [1, 3, 5, 2], skill: [1, 3, 5, 1], social: [1, 3, 5, 2, 4], theme: [3, 1, 3, 1, 3, 1] },
      },
      {
        path: '/omahahilo',
        labelKey: 'nav.omahahilo',
        icon: '½',
        page: 'OmahaHiLo',
        profile: { mood: [1, 2, 5, 1], skill: [0, 2, 5, 0], social: [1, 3, 5, 1, 4], theme: [3, 1, 3, 1, 3, 1] },
      },
      {
        path: '/bigo',
        labelKey: 'nav.bigo',
        icon: '5️⃣',
        page: 'BigO',
        profile: { mood: [1, 3, 5, 2], skill: [1, 3, 5, 1], social: [1, 3, 5, 2, 4], theme: [3, 1, 3, 1, 3, 1] },
      },
      {
        path: '/bigohilo',
        labelKey: 'nav.bigohilo',
        icon: '🅱️',
        page: 'BigOHiLo',
        profile: { mood: [1, 2, 5, 1], skill: [0, 2, 5, 0], social: [1, 3, 5, 1, 4], theme: [3, 1, 3, 1, 3, 1] },
      },
      {
        path: '/shortdeck',
        labelKey: 'nav.shortdeck',
        icon: '6️⃣',
        page: 'ShortDeck',
        profile: { mood: [2, 5, 3, 4], skill: [2, 4, 4, 2], social: [1, 3, 5, 3, 3], theme: [3, 1, 3, 1, 3, 1] },
      },
      {
        path: '/pineapple',
        labelKey: 'nav.pineapple',
        icon: '🍍',
        page: 'Pineapple',
        profile: { mood: [2, 4, 4, 3], skill: [2, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [3, 1, 2, 1, 3, 1] },
      },
      {
        path: '/crazypineapple',
        labelKey: 'nav.crazypineapple',
        icon: '🤪',
        page: 'CrazyPineapple',
        profile: { mood: [1, 5, 3, 3], skill: [2, 4, 4, 2], social: [1, 3, 5, 3, 3], theme: [3, 1, 2, 1, 3, 1] },
      },
      {
        path: '/irishpoker',
        labelKey: 'nav.irishpoker',
        icon: '🍀',
        page: 'IrishPoker',
        profile: { mood: [1, 5, 4, 3], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 4], theme: [3, 1, 2, 1, 3, 1] },
      },
      {
        path: '/sevencardstud',
        labelKey: 'nav.sevencardstud',
        icon: '7️⃣',
        page: 'SevenCardStud',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 2, 5], theme: [2, 1, 3, 1, 2, 1] },
      },
      {
        path: '/fivecardstud',
        labelKey: 'nav.fivecardstud',
        icon: '5️⃣',
        page: 'FiveCardStud',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 4, 2], social: [1, 3, 5, 2, 5], theme: [2, 1, 3, 1, 2, 1] },
      },
      {
        path: '/razz',
        labelKey: 'nav.razz',
        icon: '🃏',
        page: 'Razz',
        profile: { mood: [2, 2, 5, 2], skill: [1, 2, 5, 1], social: [1, 3, 5, 2, 4], theme: [2, 1, 3, 1, 2, 1] },
      },
      {
        path: '/sevencardstudhilo',
        labelKey: 'nav.sevencardstudhilo',
        icon: '🎴',
        page: 'SevenCardStudHiLo',
        profile: { mood: [2, 3, 5, 2], skill: [1, 3, 5, 2], social: [1, 3, 5, 2, 5], theme: [2, 1, 3, 1, 2, 1] },
      },
      {
        path: '/badugi',
        labelKey: 'nav.badugi',
        icon: '🪷',
        page: 'Badugi',
        profile: { mood: [2, 2, 5, 2], skill: [1, 3, 5, 1], social: [1, 3, 5, 2, 4], theme: [3, 1, 1, 1, 2, 1] },
      },
      {
        path: '/deucetoseven',
        labelKey: 'nav.deucetoseven',
        icon: '🎰',
        page: 'DeuceToSeven',
        profile: { mood: [2, 2, 5, 2], skill: [1, 3, 5, 1], social: [1, 3, 5, 2, 4], theme: [3, 1, 1, 1, 2, 1] },
      },
      {
        path: '/indianpoker',
        labelKey: 'nav.indianpoker',
        icon: '🙈',
        page: 'IndianPoker',
        profile: { mood: [1, 5, 3, 4], skill: [3, 3, 3, 4], social: [0, 2, 5, 4, 3], theme: [3, 1, 1, 2, 3, 1] },
      },
      {
        path: '/videopoker',
        labelKey: 'nav.videopoker',
        icon: '📺',
        page: 'VideoPoker',
        profile: { mood: [4, 2, 3, 5], skill: [4, 5, 4, 3], social: [5, 2, 0, 4, 3], theme: [5, 1, 1, 1, 3, 2] },
      },
      {
        path: '/deuceswild',
        labelKey: 'nav.deuceswild',
        icon: '2️⃣',
        page: 'DeucesWild',
        profile: { mood: [4, 2, 4, 4], skill: [3, 5, 4, 3], social: [5, 2, 0, 3, 4], theme: [5, 1, 1, 1, 3, 2] },
      },
      {
        path: '/jokerpoker',
        labelKey: 'nav.jokerpoker',
        icon: '🤡',
        page: 'JokerPoker',
        profile: { mood: [4, 2, 3, 5], skill: [4, 5, 3, 3], social: [5, 2, 0, 4, 3], theme: [5, 1, 1, 1, 3, 2] },
      },
    ],
  },
  {
    labelKey: 'nav.category.trickTaking',
    icon: '🏆',
    routes: [
      {
        path: '/hearts',
        labelKey: 'nav.hearts',
        icon: '♥️',
        page: 'Hearts',
        profile: { mood: [3, 3, 4, 2], skill: [3, 5, 4, 3], social: [1, 3, 5, 3, 4], theme: [2, 3, 3, 2, 2, 3] },
      },
      {
        path: '/spades',
        labelKey: 'nav.spades',
        icon: '♠️',
        page: 'Spades',
        profile: { mood: [3, 3, 4, 2], skill: [3, 5, 4, 3], social: [1, 3, 5, 3, 4], theme: [2, 2, 4, 1, 3, 2] },
      },
      {
        path: '/sheepshead',
        labelKey: 'nav.sheepshead',
        icon: '🐑',
        page: 'Sheepshead',
        profile: { mood: [2, 3, 5, 2], skill: [2, 3, 5, 2], social: [1, 3, 5, 2, 5], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/doppelkopf',
        labelKey: 'nav.doppelkopf',
        icon: '🎴',
        page: 'Doppelkopf',
        profile: { mood: [2, 3, 5, 2], skill: [2, 3, 5, 2], social: [1, 3, 5, 3, 5], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/mus',
        labelKey: 'nav.mus',
        icon: '🃏',
        page: 'Mus',
        profile: { mood: [2, 4, 4, 3], skill: [2, 4, 5, 3], social: [1, 3, 5, 2, 5], theme: [2, 5, 2, 1, 4, 2] },
      },
      {
        path: '/tute',
        labelKey: 'nav.tute',
        icon: '🇪🇸',
        page: 'Tute',
        profile: { mood: [2, 3, 4, 3], skill: [3, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 4, 2, 1, 3, 2] },
      },
      {
        path: '/sueca',
        labelKey: 'nav.sueca',
        icon: '🇵🇹',
        page: 'Sueca',
        profile: { mood: [2, 3, 4, 3], skill: [3, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 3, 2, 1, 3, 2] },
      },
      {
        path: '/klaverjas',
        labelKey: 'nav.klaverjas',
        icon: '🇳🇱',
        page: 'Klaverjas',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 3, 2] },
      },
      {
        path: '/manille',
        labelKey: 'nav.manille',
        icon: '🇫🇷',
        page: 'Manille',
        profile: { mood: [2, 3, 4, 3], skill: [3, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 4, 2, 1, 3, 2] },
      },
      {
        path: '/marias',
        labelKey: 'nav.marias',
        icon: '🇨🇿',
        page: 'Marias',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/king',
        labelKey: 'nav.king',
        icon: '👑',
        page: 'King',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/tysiac',
        labelKey: 'nav.tysiac',
        icon: '🇵🇱',
        page: 'Tysiac',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/calabresella',
        labelKey: 'nav.calabresella',
        icon: '🇮🇹',
        page: 'Calabresella',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/ombre',
        labelKey: 'nav.ombre',
        icon: '🇪🇸',
        page: 'Ombre',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/ulti',
        labelKey: 'nav.ulti',
        icon: '🇭🇺',
        page: 'Ulti',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/scarto',
        labelKey: 'nav.scarto',
        icon: '🃏',
        page: 'Scarto',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/cego',
        labelKey: 'nav.cego',
        icon: '🃏',
        page: 'Cego',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/frenchtarot',
        labelKey: 'nav.frenchtarot',
        icon: '🃏',
        page: 'FrenchTarot',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/koenigrufen',
        labelKey: 'nav.koenigrufen',
        icon: '🃏',
        page: 'Koenigrufen',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 2], social: [1, 3, 5, 3, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/cinch',
        labelKey: 'nav.cinch',
        icon: '🃏',
        page: 'Cinch',
        profile: { mood: [2, 3, 5, 3], skill: [2, 4, 5, 3], social: [1, 3, 5, 3, 5], theme: [3, 2, 5, 1, 3, 2] },
      },
      {
        path: '/loo',
        labelKey: 'nav.loo',
        icon: '🕯️',
        page: 'Loo',
        profile: { mood: [3, 3, 5, 4], skill: [3, 3, 5, 4], social: [1, 3, 5, 3, 5], theme: [3, 2, 5, 1, 3, 2] },
      },
      {
        path: '/basra',
        labelKey: 'nav.basra',
        icon: '🐟',
        page: 'Basra',
        profile: { mood: [3, 4, 4, 3], skill: [3, 3, 4, 3], social: [1, 3, 5, 3, 5], theme: [3, 2, 5, 1, 3, 2] },
      },
      {
        path: '/hachihachi',
        labelKey: 'nav.hachihachi',
        icon: '🎴',
        page: 'HachiHachi',
        profile: { mood: [4, 4, 3, 3], skill: [3, 4, 4, 3], social: [1, 2, 5, 4, 5], theme: [5, 2, 3, 1, 2, 4] },
      },
      {
        path: '/koikoi',
        labelKey: 'nav.koikoi',
        icon: '🎴',
        page: 'KoiKoi',
        profile: { mood: [4, 4, 3, 3], skill: [3, 4, 3, 3], social: [1, 2, 5, 3, 5], theme: [5, 2, 3, 1, 2, 4] },
      },
      {
        path: '/gostop',
        labelKey: 'nav.gostop',
        icon: '🐦',
        page: 'GoStop',
        profile: { mood: [4, 4, 3, 3], skill: [3, 4, 3, 3], social: [1, 2, 5, 3, 5], theme: [5, 2, 3, 1, 2, 4] },
      },
      {
        path: '/tablanet',
        labelKey: 'nav.tablanet',
        icon: '🎣',
        page: 'Tablanet',
        profile: { mood: [3, 4, 4, 3], skill: [3, 3, 4, 3], social: [1, 3, 5, 3, 5], theme: [3, 2, 5, 1, 3, 2] },
      },
      {
        path: '/sedma',
        labelKey: 'nav.sedma',
        icon: '🇨🇿',
        page: 'Sedma',
        profile: { mood: [3, 4, 3, 3], skill: [4, 4, 3, 2], social: [1, 3, 5, 4, 3], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/knockoutwhist',
        labelKey: 'nav.knockoutwhist',
        icon: '🇬🇧',
        page: 'KnockoutWhist',
        profile: { mood: [2, 4, 3, 4], skill: [4, 4, 2, 3], social: [1, 3, 5, 4, 3], theme: [3, 3, 3, 1, 2, 2] },
      },
      {
        path: '/spoilfive',
        labelKey: 'nav.spoilfive',
        icon: '🇮🇪',
        page: 'SpoilFive',
        profile: { mood: [3, 4, 4, 3], skill: [3, 4, 4, 2], social: [1, 2, 5, 5, 4], theme: [3, 3, 4, 1, 2, 2] },
      },
      {
        path: '/pitch',
        labelKey: 'nav.pitch',
        icon: '🎯',
        page: 'Pitch',
        profile: { mood: [3, 3, 4, 2], skill: [3, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [1, 1, 5, 1, 2, 1] },
      },
      {
        path: '/twotenjack',
        labelKey: 'nav.twotenjack',
        icon: '🎯',
        page: 'TwoTenJack',
        profile: { mood: [3, 4, 3, 3], skill: [4, 4, 3, 2], social: [1, 3, 5, 4, 3], theme: [1, 1, 1, 5, 2, 3] },
      },
      {
        path: '/ohhell',
        labelKey: 'nav.ohhell',
        icon: '🔔',
        page: 'OhHell',
        profile: { mood: [2, 4, 4, 3], skill: [3, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 3, 3, 2, 3, 2] },
      },
      {
        path: '/wizard',
        labelKey: 'nav.wizard',
        icon: '🧙',
        page: 'Wizard',
        profile: { mood: [2, 4, 4, 3], skill: [3, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 3, 3, 2, 3, 2] },
      },
      {
        path: '/ninetynine',
        labelKey: 'nav.ninetynine',
        icon: '💯',
        page: 'NinetyNine',
        profile: { mood: [2, 3, 5, 2], skill: [2, 3, 5, 2], social: [1, 3, 5, 3, 3], theme: [2, 3, 3, 2, 3, 2] },
      },
      {
        path: '/euchre',
        labelKey: 'nav.euchre',
        icon: '🎩',
        page: 'Euchre',
        profile: { mood: [2, 4, 3, 3], skill: [3, 5, 4, 3], social: [1, 3, 5, 3, 3], theme: [2, 2, 4, 1, 3, 2] },
      },
      {
        path: '/bridge',
        labelKey: 'nav.bridge',
        icon: '🌉',
        page: 'Bridge',
        profile: { mood: [1, 2, 5, 0], skill: [0, 2, 5, 0], social: [1, 3, 5, 0, 4], theme: [3, 5, 2, 1, 3, 3] },
      },
      {
        path: '/napoleon',
        labelKey: 'nav.napoleon',
        icon: '👑',
        page: 'Napoleon',
        profile: { mood: [2, 3, 5, 2], skill: [2, 3, 5, 1], social: [1, 3, 5, 2, 4], theme: [3, 5, 1, 2, 3, 3] },
      },
      {
        path: '/whist',
        labelKey: 'nav.whist',
        icon: '🎴',
        page: 'Whist',
        profile: { mood: [3, 3, 4, 2], skill: [3, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/catchten',
        labelKey: 'nav.catchten',
        icon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        page: 'CatchTen',
        profile: { mood: [3, 3, 4, 2], skill: [3, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/belote',
        labelKey: 'nav.belote',
        icon: '🇫🇷',
        page: 'Belote',
        profile: { mood: [2, 3, 4, 2], skill: [2, 4, 4, 2], social: [1, 3, 5, 2, 4], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/jass',
        labelKey: 'nav.jass',
        icon: '🇨🇭',
        page: 'Jass',
        profile: { mood: [2, 3, 4, 2], skill: [2, 4, 4, 2], social: [1, 3, 5, 2, 4], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/watten',
        labelKey: 'nav.watten',
        icon: '🇦🇹',
        page: 'Watten',
        profile: { mood: [2, 3, 4, 2], skill: [2, 4, 4, 2], social: [1, 3, 5, 2, 4], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/gaigel',
        labelKey: 'nav.gaigel',
        icon: '🇩🇪',
        page: 'Gaigel',
        profile: { mood: [2, 3, 4, 2], skill: [2, 4, 4, 2], social: [1, 3, 5, 2, 4], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/mighty',
        labelKey: 'nav.mighty',
        icon: '👊',
        page: 'Mighty',
        profile: { mood: [2, 4, 5, 2], skill: [2, 3, 5, 2], social: [1, 3, 5, 2, 5], theme: [2, 2, 1, 3, 2, 2] },
      },
      {
        path: '/fivehundred',
        labelKey: 'nav.fivehundred',
        icon: '🎯',
        page: 'FiveHundred',
        profile: { mood: [2, 4, 5, 2], skill: [2, 3, 5, 2], social: [1, 3, 5, 2, 5], theme: [2, 2, 1, 3, 2, 2] },
      },
      {
        path: '/rook',
        labelKey: 'nav.rook',
        icon: '🐦',
        page: 'Rook',
        profile: { mood: [2, 4, 5, 2], skill: [2, 3, 5, 2], social: [1, 3, 5, 2, 5], theme: [2, 2, 1, 3, 2, 2] },
      },
      {
        path: '/bidwhist',
        labelKey: 'nav.bidwhist',
        icon: '🃏',
        page: 'BidWhist',
        profile: { mood: [2, 4, 5, 2], skill: [2, 3, 5, 2], social: [1, 3, 5, 2, 5], theme: [2, 2, 1, 3, 2, 2] },
      },
      {
        path: '/solowhist',
        labelKey: 'nav.solowhist',
        icon: '🇬🇧',
        page: 'SoloWhist',
        profile: { mood: [2, 3, 5, 2], skill: [2, 3, 5, 2], social: [1, 3, 5, 2, 5], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/fortyfives',
        labelKey: 'nav.fortyfives',
        icon: '🍀',
        page: 'FortyFives',
        profile: { mood: [3, 4, 5, 2], skill: [2, 3, 5, 2], social: [1, 2, 5, 4, 5], theme: [2, 4, 1, 1, 3, 3] },
      },
      {
        path: '/nap',
        labelKey: 'nav.nap',
        icon: '🎩',
        page: 'Nap',
        profile: { mood: [3, 4, 4, 2], skill: [2, 3, 4, 3], social: [1, 3, 5, 2, 4], theme: [2, 4, 1, 1, 3, 3] },
      },
      {
        path: '/preference',
        labelKey: 'nav.preference',
        icon: '🪆',
        page: 'Preference',
        profile: { mood: [2, 3, 5, 2], skill: [1, 3, 5, 2], social: [1, 3, 5, 3, 4], theme: [2, 4, 1, 1, 2, 3] },
      },
      {
        path: '/twentynine',
        labelKey: 'nav.twentynine',
        icon: '🪔',
        page: 'TwentyNine',
        profile: { mood: [3, 4, 5, 2], skill: [2, 3, 5, 2], social: [1, 2, 5, 4, 5], theme: [2, 4, 1, 1, 3, 3] },
      },
      {
        path: '/courtpiece',
        labelKey: 'nav.courtpiece',
        icon: '👑',
        page: 'CourtPiece',
        profile: { mood: [3, 4, 5, 2], skill: [2, 3, 5, 2], social: [1, 2, 5, 4, 5], theme: [2, 4, 1, 1, 3, 3] },
      },
      {
        path: '/bezique',
        labelKey: 'nav.bezique',
        icon: '💞',
        page: 'Bezique',
        profile: { mood: [2, 3, 5, 2], skill: [1, 3, 5, 1], social: [1, 3, 5, 2, 4], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/ecarte',
        labelKey: 'nav.ecarte',
        icon: '🃏',
        page: 'Ecarte',
        profile: { mood: [2, 3, 5, 2], skill: [1, 3, 5, 1], social: [1, 3, 5, 2, 4], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/threecardbrag',
        labelKey: 'nav.threecardbrag',
        icon: '🎲',
        page: 'ThreeCardBrag',
        profile: { mood: [3, 4, 4, 5], skill: [1, 2, 4, 3], social: [1, 4, 5, 3, 5], theme: [2, 4, 1, 5, 2, 2] },
      },
      {
        path: '/teenpatti',
        labelKey: 'nav.teenpatti',
        icon: '🎴',
        page: 'TeenPatti',
        profile: { mood: [3, 4, 4, 5], skill: [1, 2, 4, 3], social: [1, 4, 5, 3, 5], theme: [2, 4, 1, 5, 2, 2] },
      },
      {
        path: '/guts',
        labelKey: 'nav.guts',
        icon: '😤',
        page: 'Guts',
        profile: { mood: [2, 5, 2, 5], skill: [4, 2, 1, 4], social: [1, 4, 5, 2, 4], theme: [4, 2, 2, 2, 4, 1] },
      },
      {
        path: '/anaconda',
        labelKey: 'nav.anaconda',
        icon: '🐍',
        page: 'Anaconda',
        profile: { mood: [2, 5, 3, 4], skill: [3, 3, 2, 4], social: [1, 4, 5, 3, 4], theme: [3, 3, 2, 3, 4, 1] },
      },
      {
        path: '/bouillotte',
        labelKey: 'nav.bouillotte',
        icon: '🕯️',
        page: 'Bouillotte',
        profile: { mood: [2, 5, 2, 5], skill: [3, 2, 2, 4], social: [1, 4, 5, 2, 4], theme: [4, 2, 2, 2, 4, 1] },
      },
      {
        path: '/primero',
        labelKey: 'nav.primero',
        icon: '👑',
        page: 'Primero',
        profile: { mood: [2, 5, 2, 5], skill: [3, 2, 2, 4], social: [1, 4, 5, 2, 4], theme: [4, 2, 2, 2, 4, 1] },
      },
      {
        path: '/michigan',
        labelKey: 'nav.michigan',
        icon: '🐎',
        page: 'Michigan',
        profile: { mood: [3, 4, 3, 4], skill: [4, 2, 2, 3], social: [1, 4, 5, 2, 4], theme: [3, 2, 2, 3, 3, 2] },
      },
      {
        path: '/spoons',
        labelKey: 'nav.spoons',
        icon: '🥄',
        page: 'Spoons',
        profile: { mood: [5, 5, 2, 4], skill: [4, 3, 1, 2], social: [1, 5, 5, 2, 5], theme: [3, 2, 1, 2, 5, 2] },
      },
      {
        path: '/kemps',
        labelKey: 'nav.kemps',
        icon: '🤝',
        page: 'Kemps',
        profile: { mood: [4, 5, 3, 4], skill: [2, 4, 3, 3], social: [1, 5, 5, 3, 5], theme: [3, 3, 2, 2, 4, 3] },
      },
      {
        path: '/cuckoo',
        labelKey: 'nav.cuckoo',
        icon: '🐦',
        page: 'Cuckoo',
        profile: { mood: [4, 5, 2, 4], skill: [4, 2, 1, 2], social: [1, 4, 5, 3, 4], theme: [3, 2, 1, 3, 4, 2] },
      },
      {
        path: '/pishti',
        labelKey: 'nav.pishti',
        icon: '🇹🇷',
        page: 'Pishti',
        profile: { mood: [4, 4, 3, 4], skill: [3, 3, 2, 2], social: [1, 4, 5, 3, 4], theme: [3, 2, 1, 3, 3, 2] },
      },
      {
        path: '/cuarenta',
        labelKey: 'nav.cuarenta',
        icon: '🇪🇨',
        page: 'Cuarenta',
        profile: { mood: [4, 4, 3, 4], skill: [3, 3, 3, 2], social: [1, 4, 5, 3, 4], theme: [3, 2, 1, 3, 3, 2] },
      },
      {
        path: '/faro',
        labelKey: 'nav.faro',
        icon: '🎴',
        page: 'Faro',
        profile: { mood: [5, 3, 2, 4], skill: [2, 2, 4, 1], social: [5, 2, 1, 3, 2], theme: [1, 1, 5, 1, 2, 2] },
      },
      {
        path: '/openfacechinese',
        labelKey: 'nav.openfacechinese',
        icon: '🀄',
        page: 'OpenFaceChinese',
        profile: { mood: [3, 4, 4, 3], skill: [2, 3, 5, 2], social: [4, 3, 2, 3, 3], theme: [1, 2, 4, 1, 2, 3] },
      },
      {
        path: '/piquet',
        labelKey: 'nav.piquet',
        icon: '🎴',
        page: 'Piquet',
        profile: { mood: [2, 2, 5, 2], skill: [1, 3, 5, 1], social: [1, 3, 5, 2, 4], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/callbreak',
        labelKey: 'nav.callbreak',
        icon: '🃏',
        page: 'CallBreak',
        profile: { mood: [2, 4, 4, 3], skill: [2, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 2, 1, 3, 2, 2] },
      },
      {
        path: '/tarneeb',
        labelKey: 'nav.tarneeb',
        icon: '🎴',
        page: 'Tarneeb',
        profile: { mood: [2, 4, 4, 3], skill: [3, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 3, 1, 3, 2, 3] },
      },
      {
        path: '/briscola',
        labelKey: 'nav.briscola',
        icon: '🇮🇹',
        page: 'Briscola',
        profile: { mood: [3, 4, 3, 4], skill: [4, 4, 3, 3], social: [1, 3, 5, 4, 3], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/schnapsen',
        labelKey: 'nav.schnapsen',
        icon: '🇦🇹',
        page: 'Schnapsen',
        profile: { mood: [2, 4, 4, 3], skill: [5, 4, 2, 2], social: [1, 2, 5, 4, 3], theme: [2, 4, 1, 1, 2, 3] },
      },
    ],
  },
  {
    labelKey: 'nav.category.matching',
    icon: '🔄',
    routes: [
      {
        path: '/oldmaid',
        labelKey: 'nav.oldmaid',
        icon: '👵',
        page: 'OldMaid',
        profile: { mood: [3, 5, 1, 4], skill: [5, 2, 1, 5], social: [0, 2, 5, 5, 2], theme: [2, 2, 2, 5, 3, 3] },
      },
      {
        path: '/doubt',
        labelKey: 'nav.doubt',
        icon: '🤥',
        page: 'Doubt',
        profile: { mood: [2, 5, 2, 3], skill: [4, 4, 3, 4], social: [0, 2, 5, 4, 3], theme: [2, 2, 2, 5, 3, 3] },
      },
      {
        path: '/durak',
        labelKey: 'nav.durak',
        icon: '🃏',
        page: 'Durak',
        profile: { mood: [2, 4, 4, 3], skill: [2, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 3, 1, 1, 2, 2] },
      },
      {
        path: '/daifugo',
        labelKey: 'nav.daifugo',
        icon: '💰',
        page: 'Daifugo',
        profile: { mood: [2, 5, 3, 3], skill: [3, 5, 4, 2], social: [0, 2, 5, 3, 3], theme: [2, 1, 1, 5, 2, 3] },
      },
      {
        path: '/bigtwo',
        labelKey: 'nav.bigtwo',
        icon: '🃏',
        page: 'BigTwo',
        profile: { mood: [2, 5, 3, 3], skill: [3, 4, 4, 2], social: [0, 2, 5, 3, 4], theme: [2, 2, 2, 4, 2, 3] },
      },
      {
        path: '/tienlen',
        labelKey: 'nav.tienlen',
        icon: '🐉',
        page: 'TienLen',
        profile: { mood: [2, 5, 3, 3], skill: [3, 4, 4, 2], social: [0, 2, 5, 3, 4], theme: [2, 2, 2, 4, 2, 3] },
      },
      {
        path: '/zheng',
        labelKey: 'nav.zheng',
        icon: '🀄',
        page: 'Zheng',
        profile: { mood: [2, 5, 3, 3], skill: [3, 4, 4, 2], social: [0, 2, 5, 3, 4], theme: [2, 2, 2, 4, 2, 3] },
      },
      {
        path: '/president',
        labelKey: 'nav.president',
        icon: '🎩',
        page: 'President',
        profile: { mood: [2, 5, 3, 3], skill: [3, 5, 4, 2], social: [0, 2, 5, 3, 3], theme: [2, 2, 3, 3, 3, 2] },
      },
      {
        path: '/cassino',
        labelKey: 'nav.cassino',
        icon: '🎣',
        page: 'Cassino',
        profile: { mood: [3, 3, 4, 2], skill: [3, 4, 3, 3], social: [1, 3, 5, 3, 4], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/scopa',
        labelKey: 'nav.scopa',
        icon: '🇮🇹',
        page: 'Scopa',
        profile: { mood: [3, 3, 4, 2], skill: [3, 4, 3, 3], social: [1, 3, 5, 3, 4], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/scopone',
        labelKey: 'nav.scopone',
        icon: '🇮🇹',
        page: 'Scopone',
        profile: { mood: [3, 3, 4, 2], skill: [3, 4, 4, 3], social: [1, 2, 4, 4, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/escoba',
        labelKey: 'nav.escoba',
        icon: '🇪🇸',
        page: 'Escoba',
        profile: { mood: [3, 3, 4, 2], skill: [3, 4, 4, 3], social: [1, 2, 4, 4, 5], theme: [2, 4, 2, 1, 2, 3] },
      },
      {
        path: '/barbu',
        labelKey: 'nav.barbu',
        icon: '🧔',
        page: 'Barbu',
        profile: { mood: [3, 4, 3, 2], skill: [5, 5, 2, 3], social: [1, 2, 5, 4, 3], theme: [2, 3, 2, 2, 2, 3] },
      },
      {
        path: '/sevens',
        labelKey: 'nav.sevens',
        icon: '7️⃣',
        page: 'Sevens',
        profile: { mood: [3, 4, 2, 4], skill: [5, 4, 2, 4], social: [0, 2, 5, 4, 2], theme: [2, 2, 1, 4, 2, 3] },
      },
      {
        path: '/crazyeights',
        labelKey: 'nav.crazyeights',
        icon: '8️⃣',
        page: 'CrazyEights',
        profile: { mood: [3, 5, 2, 5], skill: [5, 3, 1, 5], social: [1, 3, 5, 5, 2], theme: [2, 2, 3, 3, 3, 3] },
      },
      {
        path: '/prsi',
        labelKey: 'nav.prsi',
        icon: '🇨🇿',
        page: 'Prsi',
        profile: { mood: [3, 5, 2, 5], skill: [5, 3, 1, 5], social: [1, 3, 5, 5, 2], theme: [2, 2, 3, 3, 3, 3] },
      },
      {
        path: '/pageone',
        labelKey: 'nav.pageone',
        icon: '📄',
        page: 'PageOne',
        profile: { mood: [3, 5, 2, 5], skill: [5, 3, 1, 5], social: [1, 3, 5, 5, 2], theme: [2, 1, 1, 5, 2, 3] },
      },
      {
        path: '/macau',
        labelKey: 'nav.macau',
        icon: '🎴',
        page: 'Macau',
        profile: { mood: [4, 5, 1, 5], skill: [5, 3, 1, 4], social: [1, 3, 5, 5, 2], theme: [2, 2, 3, 4, 2, 3] },
      },
      {
        path: '/mao',
        labelKey: 'nav.mao',
        icon: '🤫',
        page: 'Mao',
        profile: { mood: [4, 5, 2, 5], skill: [4, 4, 3, 4], social: [1, 3, 5, 5, 2], theme: [2, 2, 4, 4, 3, 4] },
      },
      {
        path: '/russianbank',
        labelKey: 'nav.russianbank',
        icon: '🏦',
        page: 'RussianBank',
        profile: { mood: [3, 5, 2, 5], skill: [5, 4, 2, 4], social: [1, 3, 5, 5, 2], theme: [2, 2, 3, 5, 2, 3] },
      },
      {
        path: '/labellelucie',
        labelKey: 'nav.labellelucie',
        icon: '🌸',
        page: 'LaBelleLucie',
        profile: { mood: [4, 5, 2, 5], skill: [4, 3, 2, 4], social: [5, 1, 1, 5, 1], theme: [2, 1, 2, 5, 2, 3] },
      },
      {
        path: '/simplesimon',
        labelKey: 'nav.simplesimon',
        icon: '🕷️',
        page: 'SimpleSimon',
        profile: { mood: [4, 5, 2, 5], skill: [4, 4, 2, 4], social: [5, 1, 1, 5, 1], theme: [2, 1, 2, 5, 2, 3] },
      },
      {
        path: '/doubleklondike',
        labelKey: 'nav.doubleklondike',
        icon: '🃏',
        page: 'DoubleKlondike',
        profile: { mood: [4, 5, 2, 5], skill: [4, 4, 2, 4], social: [5, 1, 1, 5, 1], theme: [2, 1, 2, 5, 2, 3] },
      },
      {
        path: '/blackhole',
        labelKey: 'nav.blackhole',
        icon: '🕳️',
        page: 'BlackHole',
        profile: { mood: [4, 5, 1, 5], skill: [3, 5, 2, 4], social: [5, 1, 1, 5, 1], theme: [2, 1, 1, 5, 2, 4] },
      },
      {
        path: '/speed',
        labelKey: 'nav.speed',
        icon: '⚡',
        page: 'Speed',
        profile: { mood: [3, 5, 1, 5], skill: [5, 3, 1, 5], social: [0, 2, 5, 5, 2], theme: [1, 1, 2, 3, 2, 2] },
      },
      {
        path: '/gofish',
        labelKey: 'nav.gofish',
        icon: '🐟',
        page: 'GoFish',
        profile: { mood: [3, 4, 2, 4], skill: [5, 2, 1, 5], social: [0, 2, 5, 4, 2], theme: [2, 2, 3, 3, 3, 3] },
      },
      {
        path: '/pinochle',
        labelKey: 'nav.pinochle',
        icon: '🎯',
        page: 'Pinochle',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 1], social: [1, 3, 5, 2, 4], theme: [2, 3, 3, 1, 2, 2] },
      },
      {
        path: '/pigtail',
        labelKey: 'nav.pigtail',
        icon: '🐷',
        page: 'PigsTail',
        profile: { mood: [3, 5, 1, 5], skill: [5, 3, 1, 5], social: [0, 2, 5, 5, 2], theme: [2, 3, 1, 4, 2, 3] },
      },
      {
        path: '/war',
        labelKey: 'nav.war',
        icon: '⚔️',
        page: 'War',
        profile: { mood: [3, 4, 1, 5], skill: [5, 1, 0, 5], social: [0, 3, 5, 5, 1], theme: [1, 1, 2, 3, 2, 2] },
      },
      {
        path: '/fiftyone',
        labelKey: 'nav.fiftyone',
        icon: '5️⃣',
        page: 'FiftyOne',
        profile: { mood: [3, 4, 2, 4], skill: [4, 3, 2, 4], social: [0, 2, 5, 4, 2], theme: [2, 2, 1, 4, 2, 3] },
      },
      {
        path: '/trash',
        labelKey: 'nav.trash',
        icon: '🗑️',
        page: 'Trash',
        profile: { mood: [3, 4, 2, 4], skill: [5, 2, 1, 5], social: [0, 2, 5, 4, 2], theme: [2, 2, 3, 3, 3, 3] },
      },
      {
        path: '/sixcardgolf',
        labelKey: 'nav.sixcardgolf',
        icon: '⛳',
        page: 'SixCardGolf',
        profile: { mood: [3, 3, 4, 3], skill: [3, 4, 4, 3], social: [0, 3, 5, 4, 3], theme: [2, 2, 3, 3, 2, 3] },
      },
      {
        path: '/doudizhu',
        labelKey: 'nav.doudizhu',
        icon: '🏠',
        page: 'Doudizhu',
        profile: { mood: [2, 5, 3, 3], skill: [3, 5, 4, 2], social: [0, 2, 5, 3, 4], theme: [2, 2, 2, 5, 2, 3] },
      },
      {
        path: '/tichu',
        labelKey: 'nav.tichu',
        icon: '🐉',
        page: 'Tichu',
        profile: { mood: [2, 5, 4, 3], skill: [2, 5, 5, 2], social: [0, 1, 5, 4, 4], theme: [2, 2, 3, 4, 2, 4] },
      },
      {
        path: '/bourre',
        labelKey: 'nav.bourre',
        icon: '🎰',
        page: 'Bourre',
        profile: { mood: [3, 4, 4, 3], skill: [2, 4, 5, 3], social: [0, 2, 5, 3, 4], theme: [5, 3, 2, 1, 4, 2] },
      },
      {
        path: '/truco',
        labelKey: 'nav.truco',
        icon: '🃏',
        page: 'Truco',
        profile: { mood: [2, 5, 4, 3], skill: [2, 4, 4, 2], social: [0, 4, 4, 3, 4], theme: [4, 4, 2, 1, 4, 2] },
      },
      {
        path: '/spiteandmalice',
        labelKey: 'nav.spiteandmalice',
        icon: '😈',
        page: 'SpiteAndMalice',
        profile: { mood: [2, 4, 4, 3], skill: [3, 4, 4, 2], social: [0, 5, 3, 3, 4], theme: [2, 2, 3, 2, 3, 2] },
      },
      {
        path: '/skat',
        labelKey: 'nav.skat',
        icon: '🇩🇪',
        page: 'Skat',
        profile: { mood: [1, 3, 5, 1], skill: [0, 3, 5, 0], social: [1, 3, 5, 1, 4], theme: [2, 5, 1, 1, 2, 3] },
      },
      {
        path: '/shithead',
        labelKey: 'nav.shithead',
        icon: '👑',
        page: 'Shithead',
        profile: { mood: [3, 5, 2, 3], skill: [4, 4, 3, 3], social: [0, 2, 5, 4, 3], theme: [2, 3, 2, 2, 3, 3] },
      },
      {
        path: '/nertz',
        labelKey: 'nav.nertz',
        icon: '🥜',
        page: 'Nertz',
        profile: { mood: [3, 5, 2, 4], skill: [3, 4, 3, 3], social: [0, 2, 5, 4, 3], theme: [2, 2, 3, 2, 3, 2] },
      },
      {
        path: '/slapjack',
        labelKey: 'nav.slapjack',
        icon: '✋',
        page: 'Slapjack',
        profile: { mood: [3, 5, 1, 5], skill: [5, 2, 1, 5], social: [0, 2, 5, 5, 2], theme: [2, 2, 3, 3, 3, 3] },
      },
      {
        path: '/egyptianratscrew',
        labelKey: 'nav.egyptianratscrew',
        icon: '🐀',
        page: 'EgyptianRatscrew',
        profile: { mood: [2, 5, 1, 5], skill: [4, 3, 2, 4], social: [0, 2, 5, 5, 2], theme: [2, 2, 3, 2, 3, 2] },
      },
    ],
  },
  {
    labelKey: 'nav.category.solitaire',
    icon: '🏔️',
    routes: [
      {
        path: '/klondike',
        labelKey: 'nav.klondike',
        icon: '⛏️',
        page: 'Klondike',
        profile: { mood: [5, 1, 3, 3], skill: [4, 5, 3, 4], social: [5, 1, 0, 3, 3], theme: [3, 3, 3, 2, 3, 3] },
      },
      {
        path: '/freecell',
        labelKey: 'nav.freecell',
        icon: '🔲',
        page: 'FreeCell',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 5, 2], social: [5, 1, 0, 2, 5], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/bakersgame',
        labelKey: 'nav.bakersgame',
        icon: '🧱',
        page: 'BakersGame',
        profile: { mood: [5, 1, 5, 2], skill: [2, 4, 5, 1], social: [5, 1, 0, 2, 5], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/eightoff',
        labelKey: 'nav.eightoff',
        icon: '🎱',
        page: 'EightOff',
        profile: { mood: [5, 1, 5, 2], skill: [2, 4, 5, 1], social: [5, 1, 0, 2, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/penguin',
        labelKey: 'nav.penguin',
        icon: '🐧',
        page: 'Penguin',
        profile: {
          mood: [5, 1, 5, 2],
          skill: [2, 4, 5, 1],
          social: [5, 1, 0, 2, 4],
          theme: [3, 3, 3, 1, 3, 3],
        },
      },
      {
        path: '/seahaventowers',
        labelKey: 'nav.seahaventowers',
        icon: '🏖️',
        page: 'SeahavenTowers',
        profile: { mood: [5, 1, 5, 2], skill: [2, 3, 5, 1], social: [5, 1, 0, 2, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/spider',
        labelKey: 'nav.spider',
        icon: '🕷️',
        page: 'Spider',
        profile: { mood: [5, 1, 5, 1], skill: [2, 4, 5, 1], social: [5, 1, 0, 1, 4], theme: [3, 3, 3, 2, 3, 3] },
      },
      {
        path: '/spiderette',
        labelKey: 'nav.spiderette',
        icon: '🕸️',
        page: 'Spiderette',
        profile: { mood: [5, 1, 4, 3], skill: [4, 4, 3, 3], social: [5, 1, 0, 3, 4], theme: [3, 3, 3, 2, 3, 3] },
      },
      {
        path: '/pyramid',
        labelKey: 'nav.pyramid',
        icon: '🔺',
        page: 'Pyramid',
        profile: { mood: [5, 2, 3, 4], skill: [4, 4, 3, 4], social: [5, 1, 0, 4, 3], theme: [3, 2, 1, 2, 2, 3] },
      },
      {
        path: '/gaps',
        labelKey: 'nav.gaps',
        icon: '🧩',
        page: 'Gaps',
        profile: { mood: [5, 1, 4, 3], skill: [3, 4, 4, 2], social: [5, 1, 0, 3, 4], theme: [2, 3, 3, 1, 2, 3] },
      },
      {
        path: '/tripeaks',
        labelKey: 'nav.tripeaks',
        icon: '⛰️',
        page: 'TriPeaks',
        profile: { mood: [5, 2, 2, 5], skill: [5, 4, 2, 5], social: [5, 1, 0, 5, 2], theme: [3, 2, 2, 2, 3, 3] },
      },
      {
        path: '/golf',
        labelKey: 'nav.golf',
        icon: '⛳',
        page: 'Golf',
        profile: { mood: [5, 2, 2, 5], skill: [5, 3, 2, 5], social: [5, 1, 0, 5, 2], theme: [3, 2, 3, 2, 3, 3] },
      },
      {
        path: '/acesup',
        labelKey: 'nav.acesup',
        icon: '🍀',
        page: 'AcesUp',
        profile: { mood: [5, 2, 2, 5], skill: [5, 2, 1, 5], social: [5, 1, 0, 5, 2], theme: [3, 2, 3, 2, 3, 3] },
      },
      {
        path: '/memory',
        labelKey: 'nav.memory',
        icon: '🧠',
        page: 'Memory',
        profile: { mood: [4, 3, 3, 4], skill: [5, 2, 1, 5], social: [5, 1, 3, 4, 3], theme: [2, 2, 2, 5, 2, 3] },
      },
      {
        path: '/clocksolitaire',
        labelKey: 'nav.clocksolitaire',
        icon: '🕐',
        page: 'ClockSolitaire',
        profile: { mood: [5, 1, 1, 5], skill: [5, 2, 0, 5], social: [5, 1, 0, 5, 1], theme: [3, 3, 2, 1, 2, 3] },
      },
      {
        path: '/fortythieves',
        labelKey: 'nav.fortythieves',
        icon: '🏰',
        page: 'FortyThieves',
        profile: { mood: [5, 1, 5, 1], skill: [1, 3, 5, 0], social: [5, 1, 0, 1, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/fortyandeight',
        labelKey: 'nav.fortyandeight',
        icon: '🏰',
        page: 'FortyAndEight',
        profile: { mood: [5, 1, 5, 1], skill: [1, 3, 5, 0], social: [5, 1, 0, 1, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/sultan',
        labelKey: 'nav.sultan',
        icon: '🕌',
        page: 'Sultan',
        profile: { mood: [5, 1, 5, 1], skill: [1, 3, 5, 0], social: [5, 1, 0, 1, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/bakersdozen',
        labelKey: 'nav.bakersdozen',
        icon: '🥖',
        page: 'BakersDozen',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 3, 2, 1, 2, 3] },
      },
      {
        path: '/beleagueredcastle',
        labelKey: 'nav.beleagueredcastle',
        icon: '🏯',
        page: 'BeleagueredCastle',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/bisley',
        labelKey: 'nav.bisley',
        icon: '🎯',
        page: 'Bisley',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/terrace',
        labelKey: 'nav.terrace',
        icon: '🏔️',
        page: 'Terrace',
        profile: { mood: [5, 1, 5, 2], skill: [4, 5, 5, 3], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/braid',
        labelKey: 'nav.braid',
        icon: '🧶',
        page: 'Braid',
        profile: { mood: [5, 1, 5, 2], skill: [4, 5, 5, 3], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/pontoon',
        labelKey: 'nav.pontoon',
        icon: '🇬🇧',
        page: 'Pontoon',
        profile: { mood: [4, 3, 3, 4], skill: [4, 4, 3, 4], social: [3, 4, 2, 4, 3], theme: [5, 1, 1, 1, 3, 2] },
      },
      {
        path: '/settemezzo',
        labelKey: 'nav.settemezzo',
        icon: '🇮🇹',
        page: 'SetteEMezzo',
        profile: { mood: [4, 3, 3, 4], skill: [3, 3, 3, 4], social: [3, 4, 2, 4, 3], theme: [5, 1, 1, 1, 3, 2] },
      },
      {
        path: '/niuniu',
        labelKey: 'nav.niuniu',
        icon: '🐂',
        page: 'NiuNiu',
        profile: { mood: [5, 4, 2, 5], skill: [2, 2, 2, 5], social: [3, 4, 2, 4, 3], theme: [5, 1, 1, 1, 2, 2] },
      },
      {
        path: '/bura',
        labelKey: 'nav.bura',
        icon: '🇷🇺',
        page: 'Bura',
        profile: { mood: [4, 3, 3, 4], skill: [3, 3, 4, 3], social: [4, 3, 1, 3, 3], theme: [3, 2, 1, 1, 4, 2] },
      },
      {
        path: '/mushi',
        labelKey: 'nav.mushi',
        icon: '🎴',
        page: 'Mushi',
        profile: { mood: [4, 2, 4, 3], skill: [3, 4, 3, 3], social: [4, 3, 1, 3, 3], theme: [2, 3, 1, 1, 5, 3] },
      },
      {
        path: '/toepen',
        labelKey: 'nav.toepen',
        icon: '🍺',
        page: 'Toepen',
        profile: { mood: [5, 4, 2, 5], skill: [2, 3, 4, 4], social: [5, 2, 0, 4, 4], theme: [3, 2, 1, 1, 4, 2] },
      },
      {
        path: '/trex',
        labelKey: 'nav.trex',
        icon: '🕌',
        page: 'Trex',
        profile: { mood: [4, 4, 3, 4], skill: [3, 4, 4, 3], social: [3, 4, 2, 4, 4], theme: [3, 2, 2, 1, 4, 3] },
      },
      {
        path: '/nainjaune',
        labelKey: 'nav.nainjaune',
        icon: '🟡',
        page: 'NainJaune',
        profile: { mood: [4, 3, 3, 4], skill: [3, 3, 3, 3], social: [3, 4, 2, 4, 4], theme: [3, 2, 2, 1, 3, 3] },
      },
      {
        path: '/popejoan',
        labelKey: 'nav.popejoan',
        icon: '👑',
        page: 'PopeJoan',
        profile: { mood: [4, 3, 3, 4], skill: [3, 3, 3, 3], social: [3, 4, 2, 4, 4], theme: [3, 2, 2, 1, 3, 3] },
      },
      {
        path: '/poch',
        labelKey: 'nav.poch',
        icon: '🎰',
        page: 'Poch',
        profile: { mood: [4, 3, 3, 4], skill: [3, 4, 3, 3], social: [3, 4, 2, 4, 4], theme: [3, 2, 2, 1, 3, 3] },
      },
      {
        path: '/zwicker',
        labelKey: 'nav.zwicker',
        icon: '🎣',
        page: 'Zwicker',
        profile: { mood: [4, 3, 3, 4], skill: [3, 4, 4, 3], social: [3, 4, 2, 4, 4], theme: [3, 2, 2, 1, 3, 3] },
      },
      {
        path: '/desmoche',
        labelKey: 'nav.desmoche',
        icon: '🎴',
        page: 'Desmoche',
        profile: { mood: [4, 3, 3, 4], skill: [3, 4, 3, 3], social: [3, 4, 2, 4, 3], theme: [3, 2, 2, 1, 3, 3] },
      },
      {
        path: '/loba',
        labelKey: 'nav.loba',
        icon: '🐴',
        page: 'Loba',
        profile: { mood: [4, 3, 3, 4], skill: [3, 4, 3, 3], social: [3, 4, 2, 4, 3], theme: [3, 2, 2, 1, 3, 3] },
      },
      {
        path: '/sjavs',
        labelKey: 'nav.sjavs',
        icon: '🇫🇴',
        page: 'Sjavs',
        profile: { mood: [3, 4, 3, 3], skill: [4, 4, 3, 4], social: [2, 4, 2, 5, 4], theme: [3, 2, 2, 1, 3, 3] },
      },
      {
        path: '/laughandliedown',
        labelKey: 'nav.laughandliedown',
        icon: '🎣',
        page: 'LaughAndLieDown',
        profile: { mood: [4, 2, 4, 3], skill: [2, 3, 3, 2], social: [5, 3, 1, 4, 3], theme: [2, 2, 1, 1, 5, 2] },
      },
      {
        path: '/skitgubbe',
        labelKey: 'nav.skitgubbe',
        icon: '🃏',
        page: 'Skitgubbe',
        profile: { mood: [4, 3, 3, 4], skill: [3, 4, 3, 3], social: [4, 3, 1, 4, 3], theme: [3, 2, 1, 1, 4, 3] },
      },
      {
        path: '/chineseten',
        labelKey: 'nav.chineseten',
        icon: '🀄',
        page: 'ChineseTen',
        profile: { mood: [4, 2, 4, 3], skill: [3, 4, 3, 2], social: [4, 3, 1, 3, 3], theme: [2, 3, 1, 1, 5, 3] },
      },
      {
        path: '/congress',
        labelKey: 'nav.congress',
        icon: '🏛️',
        page: 'Congress',
        profile: { mood: [5, 1, 5, 2], skill: [4, 5, 5, 3], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/americantoad',
        labelKey: 'nav.americantoad',
        icon: '🐸',
        page: 'AmericanToad',
        profile: { mood: [5, 1, 5, 2], skill: [4, 5, 5, 3], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/windmill',
        labelKey: 'nav.windmill',
        icon: '🌬️',
        page: 'Windmill',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/duchess',
        labelKey: 'nav.duchess',
        icon: '👑',
        page: 'Duchess',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/missmilligan',
        labelKey: 'nav.missmilligan',
        icon: '👗',
        page: 'MissMilligan',
        profile: { mood: [5, 1, 5, 2], skill: [4, 5, 5, 3], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/grandfathersclock',
        labelKey: 'nav.grandfathersclock',
        icon: '🕰️',
        page: 'GrandfathersClock',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/napoleonssquare',
        labelKey: 'nav.napoleonssquare',
        icon: '🟨',
        page: 'NapoleonsSquare',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/streetsandalleys',
        labelKey: 'nav.streetsandalleys',
        icon: '🛣️',
        page: 'StreetsAndAlleys',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/kingalbert',
        labelKey: 'nav.kingalbert',
        icon: '👑',
        page: 'KingAlbert',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/flowergarden',
        labelKey: 'nav.flowergarden',
        icon: '🌸',
        page: 'FlowerGarden',
        profile: { mood: [5, 1, 5, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
      {
        path: '/canfield',
        labelKey: 'nav.canfield',
        icon: '🎩',
        page: 'Canfield',
        profile: { mood: [5, 1, 4, 3], skill: [3, 4, 4, 3], social: [5, 1, 0, 3, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/agnes',
        labelKey: 'nav.agnes',
        icon: '👑',
        page: 'Agnes',
        profile: { mood: [5, 1, 4, 3], skill: [3, 4, 4, 3], social: [5, 1, 0, 3, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/osmosis',
        labelKey: 'nav.osmosis',
        icon: '💧',
        page: 'Osmosis',
        profile: { mood: [5, 1, 4, 3], skill: [3, 4, 5, 3], social: [5, 1, 0, 3, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/bristol',
        labelKey: 'nav.bristol',
        icon: '🌉',
        page: 'Bristol',
        profile: { mood: [5, 1, 4, 3], skill: [3, 4, 5, 3], social: [5, 1, 0, 3, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/yukon',
        labelKey: 'nav.yukon',
        icon: '🏔️',
        page: 'Yukon',
        profile: { mood: [5, 1, 4, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/russiansolitaire',
        labelKey: 'nav.russiansolitaire',
        icon: '🪆',
        page: 'RussianSolitaire',
        profile: { mood: [5, 1, 5, 1], skill: [2, 4, 5, 1], social: [5, 1, 0, 1, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/cruel',
        labelKey: 'nav.cruel',
        icon: '🪓',
        page: 'Cruel',
        profile: { mood: [5, 1, 3, 3], skill: [4, 3, 3, 4], social: [5, 1, 0, 3, 3], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/scorpion',
        labelKey: 'nav.scorpion',
        icon: '🦂',
        page: 'Scorpion',
        profile: { mood: [5, 1, 5, 2], skill: [2, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/wasp',
        labelKey: 'nav.wasp',
        icon: '🐝',
        page: 'Wasp',
        profile: { mood: [5, 1, 5, 2], skill: [2, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/easthaven',
        labelKey: 'nav.easthaven',
        icon: '🏡',
        page: 'Easthaven',
        profile: { mood: [5, 1, 4, 2], skill: [3, 4, 4, 2], social: [5, 1, 0, 2, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/accordion',
        labelKey: 'nav.accordion',
        icon: '🪗',
        page: 'Accordion',
        profile: { mood: [5, 1, 4, 3], skill: [3, 4, 4, 3], social: [5, 1, 0, 3, 4], theme: [2, 3, 3, 1, 2, 3] },
      },
      {
        path: '/pokersquares',
        labelKey: 'nav.pokersquares',
        icon: '🔢',
        page: 'PokerSquares',
        profile: { mood: [5, 1, 5, 3], skill: [3, 4, 5, 2], social: [5, 1, 0, 3, 5], theme: [4, 2, 2, 1, 3, 2] },
      },
      {
        path: '/montecarlo',
        labelKey: 'nav.montecarlo',
        icon: '🎲',
        page: 'MonteCarlo',
        profile: { mood: [5, 2, 3, 4], skill: [4, 4, 2, 4], social: [5, 1, 0, 4, 3], theme: [3, 3, 2, 1, 3, 3] },
      },
      {
        path: '/calculation',
        labelKey: 'nav.calculation',
        icon: '🧮',
        page: 'Calculation',
        profile: { mood: [5, 1, 5, 2], skill: [2, 4, 5, 1], social: [5, 1, 0, 2, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/sirtommy',
        labelKey: 'nav.sirtommy',
        icon: '🎩',
        page: 'SirTommy',
        profile: { mood: [5, 1, 4, 2], skill: [2, 3, 4, 1], social: [5, 1, 0, 2, 4], theme: [3, 3, 3, 1, 3, 3] },
      },
      {
        path: '/crescent',
        labelKey: 'nav.crescent',
        icon: '🌙',
        page: 'Crescent',
        profile: { mood: [5, 1, 4, 3], skill: [3, 4, 4, 3], social: [5, 1, 0, 3, 4], theme: [3, 4, 2, 1, 2, 3] },
      },
    ],
  },
  {
    labelKey: 'nav.category.rummy',
    icon: '🍸',
    routes: [
      {
        path: '/ginrummy',
        labelKey: 'nav.ginrummy',
        icon: '🫐',
        page: 'GinRummy',
        profile: { mood: [3, 3, 4, 3], skill: [3, 5, 4, 3], social: [1, 3, 5, 3, 4], theme: [3, 2, 4, 2, 3, 2] },
      },
      {
        path: '/indianrummy',
        labelKey: 'nav.indianrummy',
        icon: '🪷',
        page: 'IndianRummy',
        profile: { mood: [3, 3, 4, 3], skill: [3, 5, 4, 3], social: [3, 3, 4, 3, 4], theme: [3, 2, 4, 2, 3, 2] },
      },
      {
        path: '/machiavelli',
        labelKey: 'nav.machiavelli',
        icon: '🏛️',
        page: 'Machiavelli',
        profile: { mood: [3, 3, 4, 3], skill: [3, 5, 4, 3], social: [3, 3, 4, 3, 4], theme: [3, 2, 4, 2, 3, 2] },
      },
      {
        path: '/pan',
        labelKey: 'nav.pan',
        icon: '🌵',
        page: 'Pan',
        profile: { mood: [3, 3, 4, 3], skill: [3, 5, 4, 3], social: [3, 3, 5, 3, 4], theme: [3, 2, 4, 2, 3, 2] },
      },
      {
        path: '/conquian',
        labelKey: 'nav.conquian',
        icon: '🇲🇽',
        page: 'Conquian',
        profile: { mood: [3, 3, 4, 3], skill: [3, 5, 4, 3], social: [1, 3, 5, 3, 4], theme: [3, 2, 4, 2, 3, 2] },
      },
      {
        path: '/chinchon',
        labelKey: 'nav.chinchon',
        icon: '🌶️',
        page: 'Chinchon',
        profile: { mood: [3, 3, 4, 3], skill: [3, 5, 4, 3], social: [1, 3, 5, 3, 4], theme: [3, 2, 4, 2, 3, 2] },
      },
      {
        path: '/threethirteen',
        labelKey: 'nav.threethirteen',
        icon: '🔢',
        page: 'ThreeThirteen',
        profile: { mood: [3, 3, 4, 3], skill: [3, 5, 4, 3], social: [1, 3, 5, 3, 4], theme: [3, 2, 4, 2, 3, 2] },
      },
      {
        path: '/tonk',
        labelKey: 'nav.tonk',
        icon: '🎯',
        page: 'Tonk',
        profile: { mood: [3, 4, 3, 4], skill: [4, 4, 3, 3], social: [1, 3, 5, 4, 3], theme: [3, 1, 3, 2, 3, 2] },
      },
      {
        path: '/thirtyone',
        labelKey: 'nav.thirtyone',
        icon: '🍺',
        page: 'ThirtyOne',
        profile: { mood: [3, 4, 3, 4], skill: [3, 4, 3, 3], social: [1, 3, 5, 4, 4], theme: [3, 1, 3, 2, 4, 2] },
      },
      {
        path: '/yaniv',
        labelKey: 'nav.yaniv',
        icon: '🎒',
        page: 'Yaniv',
        profile: { mood: [3, 4, 4, 3], skill: [4, 4, 3, 2], social: [1, 3, 5, 4, 4], theme: [3, 1, 3, 2, 3, 2] },
      },
      {
        path: '/gongzhu',
        labelKey: 'nav.gongzhu',
        icon: '🐷',
        page: 'GongZhu',
        profile: { mood: [3, 4, 4, 4], skill: [4, 5, 4, 2], social: [1, 3, 5, 4, 4], theme: [3, 1, 3, 2, 4, 3] },
      },
      {
        path: '/tressette',
        labelKey: 'nav.tressette',
        icon: '🇮🇹',
        page: 'Tressette',
        profile: { mood: [3, 4, 4, 3], skill: [3, 4, 4, 3], social: [1, 3, 5, 5, 4], theme: [3, 1, 3, 2, 4, 3] },
      },
      {
        path: '/canasta',
        labelKey: 'nav.canasta',
        icon: '🃏',
        page: 'Canasta',
        profile: { mood: [2, 3, 5, 1], skill: [1, 3, 5, 1], social: [1, 3, 5, 1, 4], theme: [2, 3, 3, 1, 2, 2] },
      },
      {
        path: '/samba',
        labelKey: 'nav.samba',
        icon: '💃',
        page: 'Samba',
        profile: { mood: [2, 3, 5, 1], skill: [1, 3, 5, 1], social: [1, 3, 5, 1, 4], theme: [2, 3, 3, 1, 2, 2] },
      },
      {
        path: '/handandfoot',
        labelKey: 'nav.handandfoot',
        icon: '🃏',
        page: 'HandAndFoot',
        profile: { mood: [2, 3, 5, 1], skill: [1, 3, 5, 1], social: [1, 3, 5, 1, 4], theme: [2, 3, 3, 1, 2, 2] },
      },
      {
        path: '/burraco',
        labelKey: 'nav.burraco',
        icon: '🎴',
        page: 'Burraco',
        profile: { mood: [2, 3, 5, 1], skill: [1, 3, 5, 1], social: [1, 3, 5, 1, 4], theme: [2, 3, 3, 1, 2, 2] },
      },
      {
        path: '/cribbage',
        labelKey: 'nav.cribbage',
        icon: '📌',
        page: 'Cribbage',
        profile: { mood: [3, 3, 4, 3], skill: [3, 5, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 5, 2, 1, 2, 3] },
      },
      {
        path: '/sevenbridge',
        labelKey: 'nav.sevenbridge',
        icon: '7️⃣',
        page: 'SevenBridge',
        profile: { mood: [3, 4, 3, 4], skill: [4, 4, 3, 3], social: [1, 3, 5, 4, 3], theme: [2, 1, 1, 5, 2, 3] },
      },
      {
        path: '/contractrummy',
        labelKey: 'nav.contractrummy',
        icon: '📜',
        page: 'ContractRummy',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 1], social: [1, 3, 5, 2, 4], theme: [2, 3, 3, 1, 2, 2] },
      },
      {
        path: '/carioca',
        labelKey: 'nav.carioca',
        icon: '🌴',
        page: 'Carioca',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 1], social: [1, 3, 5, 2, 4], theme: [2, 3, 3, 1, 2, 2] },
      },
      {
        path: '/kalooki',
        labelKey: 'nav.kalooki',
        icon: '🃏',
        page: 'Kalooki',
        profile: { mood: [2, 3, 5, 2], skill: [2, 4, 5, 1], social: [1, 3, 5, 2, 4], theme: [2, 3, 3, 1, 2, 2] },
      },
      {
        path: '/rummy500',
        labelKey: 'nav.rummy500',
        icon: '🥃',
        page: 'Rummy500',
        profile: { mood: [3, 3, 4, 3], skill: [3, 4, 4, 2], social: [1, 3, 5, 3, 4], theme: [2, 2, 4, 2, 3, 2] },
      },
      {
        path: '/beggarmyneighbour',
        labelKey: 'nav.beggarmyneighbour',
        icon: '🪙',
        page: 'BeggarMyNeighbour',
        profile: { mood: [3, 4, 1, 5], skill: [5, 1, 0, 5], social: [0, 3, 5, 5, 1], theme: [1, 2, 2, 3, 2, 2] },
      },
      {
        path: '/allfours',
        labelKey: 'nav.allfours',
        icon: '🃏',
        page: 'AllFours',
        profile: { mood: [3, 4, 3, 3], skill: [2, 4, 3, 2], social: [0, 5, 2, 2, 3], theme: [1, 2, 3, 3, 2, 2] },
      },
    ],
  },
] as const;

/** Flat list of all game routes (derived from categories) for routing. */
export const gameRoutes: readonly GameRoute[] = gameCategories.flatMap((c) => c.routes);
